import { SearchX } from "lucide-react";
import { useMemo, useState } from "react";
import type { ExerciseProgress, ExerciseStatus, TrainingExercise } from "./training";
import { categoryLabels, levelLabels } from "./training";
import { ExerciseCard } from "./ExerciseCard";

export function ExerciseLibrary({ exercises, progress, onOpen, onReset }: { exercises: TrainingExercise[]; progress: Record<string, ExerciseProgress>; onOpen: (exercise: TrainingExercise) => void; onReset: (id: string) => void }) {
  const [query, setQuery] = useState(""); const [difficulty, setDifficulty] = useState("all"); const [status, setStatus] = useState("all"); const [category, setCategory] = useState("all"); const [sort, setSort] = useState("priority");
  const filtered = useMemo(() => exercises.filter((exercise) => `${exercise.title} ${exercise.topicTitle}`.toLocaleLowerCase("pt-BR").includes(query.toLocaleLowerCase("pt-BR")) && (difficulty === "all" || exercise.difficulty === difficulty) && (status === "all" || progress[exercise.id]?.status === status) && (category === "all" || exercise.category === category)).sort((a, b) => sort === "duration" ? a.estimatedMinutes - b.estimatedMinutes : ({ high: 0, medium: 1, low: 2 }[a.priority] - { high: 0, medium: 1, low: 2 }[b.priority])), [exercises, progress, query, difficulty, status, category, sort]);
  const fieldClass = "min-h-11 rounded-xl border border-line bg-white px-3 text-sm focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-focus";
  return <section aria-labelledby="exercise-library-title"><h2 id="exercise-library-title" className="text-xl font-semibold">Biblioteca de exercícios</h2><p className="mt-1 text-sm text-muted">Práticas simuladas, sem posições reais ou correção automática.</p><div className="mt-4 grid gap-3 rounded-2xl border border-line bg-white p-4 md:grid-cols-2 xl:grid-cols-5"><label className="xl:col-span-2"><span className="mb-1 block text-xs font-semibold">Buscar por título ou tema</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Ex.: finais" className={`${fieldClass} w-full`} /></label><Filter label="Dificuldade" value={difficulty} onChange={setDifficulty} options={[["all", "Todas"], ...Object.entries(levelLabels)]} className={fieldClass} /><Filter label="Status" value={status} onChange={setStatus} options={[["all", "Todos"], ["not_started", "Não iniciado"], ["in_progress", "Em andamento"], ["completed", "Concluído"] satisfies [ExerciseStatus, string]]} className={fieldClass} /><Filter label="Categoria" value={category} onChange={setCategory} options={[["all", "Todas"], ...Object.entries(categoryLabels)]} className={fieldClass} /><Filter label="Ordenar" value={sort} onChange={setSort} options={[["priority", "Prioridade"], ["duration", "Duração"]]} className={fieldClass} /></div>{filtered.length ? <div className="mt-4 grid gap-4 lg:grid-cols-2">{filtered.map((exercise) => <ExerciseCard key={exercise.id} exercise={exercise} progress={progress[exercise.id] ?? { status: "not_started", progress: 0, completedAt: null }} onOpen={() => onOpen(exercise)} onReset={() => onReset(exercise.id)} />)}</div> : <div className="mt-4 rounded-2xl border border-dashed border-line-strong bg-white px-6 py-14 text-center"><SearchX className="mx-auto text-neutral-400" size={36} /><h3 className="mt-4 text-lg font-semibold">Nenhum exercício encontrado</h3><p className="mt-2 text-sm text-muted">Ajuste a busca ou os filtros selecionados.</p></div>}</section>;
}

function Filter({ label, value, onChange, options, className }: { label: string; value: string; onChange: (value: string) => void; options: [string, string][]; className: string }) { return <label><span className="mb-1 block text-xs font-semibold">{label}</span><select value={value} onChange={(event) => onChange(event.target.value)} className={`${className} w-full`}>{options.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label>; }
