"use client";
import { ChevronRight, CheckCircle2, X } from "lucide-react";
import { useEffect, useRef } from "react";
import type { ExerciseProgress, TrainingExercise } from "./training";

export function ExerciseDialog({ exercise, progress, onClose, onStart, onAdvance, onComplete }: { exercise: TrainingExercise | null; progress?: ExerciseProgress; onClose: () => void; onStart: () => void; onAdvance: () => void; onComplete: () => void }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { const dialog = ref.current; if (exercise && !dialog?.open) dialog?.showModal(); if (!exercise && dialog?.open) dialog.close(); }, [exercise]);
  return <dialog ref={ref} onCancel={(event) => { event.preventDefault(); onClose(); }} onClose={onClose} aria-labelledby="exercise-dialog-title" aria-describedby="exercise-dialog-description" className="m-auto max-h-[90vh] w-[calc(100%-2rem)] max-w-xl overflow-y-auto rounded-2xl border border-line bg-white p-0 shadow-2xl backdrop:bg-black/60">{exercise && progress && <><div className="flex items-start justify-between gap-3 border-b border-line p-5"><div><p className="section-kicker">Exercício demonstrativo</p><h2 id="exercise-dialog-title" className="text-xl font-semibold">{exercise.title}</h2></div><button type="button" onClick={onClose} aria-label="Fechar exercício" className="rounded-lg p-2 hover:bg-neutral-100 focus-visible:outline-2"><X size={20} /></button></div><div className="p-5"><p id="exercise-dialog-description" className="text-sm leading-6 text-muted">Leia cada cenário simulado e escolha mentalmente um plano. As posições e a resolução completa serão implementadas futuramente; não há motor de xadrez nesta demonstração.</p><div className="mt-5 rounded-xl bg-neutral-100 p-4"><p className="text-xs font-bold uppercase text-muted">Instruções</p><ol className="mt-2 list-inside list-decimal space-y-2 text-sm"><li>Identifique o tema principal.</li><li>Liste lances candidatos sem movê-los no tabuleiro.</li><li>Compare sua ideia com a explicação demonstrativa.</li></ol></div><p className="mt-4 text-sm font-semibold">Progresso atual: {progress.progress}% · {progress.status === "completed" ? "concluído" : progress.status === "in_progress" ? "em andamento" : "não iniciado"}</p></div><div className="flex flex-wrap justify-end gap-2 border-t border-line bg-neutral-50 p-4">{progress.status === "not_started" && <button type="button" onClick={onStart} className="rounded-xl bg-neutral-950 px-4 py-2.5 text-sm font-semibold text-white">Começar demonstração</button>}{progress.status === "in_progress" && <><button type="button" onClick={onAdvance} className="inline-flex items-center gap-2 rounded-xl border border-line bg-white px-4 py-2.5 text-sm font-semibold">Próxima etapa <ChevronRight size={16} /></button><button type="button" onClick={onComplete} className="inline-flex items-center gap-2 rounded-xl bg-neutral-950 px-4 py-2.5 text-sm font-semibold text-white"><CheckCircle2 size={16} />Concluir</button></>}{progress.status === "completed" && <button type="button" onClick={onClose} className="rounded-xl bg-neutral-950 px-4 py-2.5 text-sm font-semibold text-white">Fechar</button>}</div></>}</dialog>;
}
