import { CheckCircle2, TrendingUp } from "lucide-react";
import type { GameAnalysis } from "@/lib/types/chess";
import { categoryLabels, getTopicIdsForCategory, type TopicRecommendation } from "./training";

export function StrengthsAndWeaknesses({ analyses, topics }: { analyses: GameAnalysis[]; topics: TopicRecommendation[] }) {
  const strengths = count(analyses.flatMap((item) => item.strengths));
  const weaknesses = count(analyses.flatMap((item) => item.weaknesses));
  const categoryCounts = analyses.flatMap((item) => item.errorCategories).reduce<Map<string, number>>((map, item) => map.set(categoryLabels[item], (map.get(categoryLabels[item]) ?? 0) + 1), new Map());
  const opportunities = [...weaknesses, ...categoryCounts].sort((a, b) => b[1] - a[1]).slice(0, 6);
  return <section aria-label="Pontos fortes e pontos a melhorar" className="grid gap-4 lg:grid-cols-2"><List title="Pontos fortes" intro="Recursos recorrentes que vale preservar." icon={CheckCircle2} items={strengths.slice(0, 6).map(([name, frequency]) => ({ name, frequency, detail: "Padrão positivo observado nas análises simuladas." }))} /><List title="Pontos a melhorar" intro="Áreas recomendadas para o próximo ciclo de estudo." icon={TrendingUp} items={opportunities.map(([name, frequency]) => { const category = Object.entries(categoryLabels).find(([, label]) => label === name)?.[0]; const topic = category ? topics.find((item) => getTopicIdsForCategory(category as keyof typeof categoryLabels).includes(item.id)) : topics.find((item) => item.title.toLocaleLowerCase("pt-BR").includes(name.toLocaleLowerCase("pt-BR"))); return { name, frequency, detail: topic ? `Vale revisar este padrão com o tema “${topic.title}”.` : "Tema com oportunidade de evolução nas próximas sessões." }; })} /></section>;
}
function count(items: string[]): [string, number][] { return [...items.reduce<Map<string, number>>((map, item) => map.set(item, (map.get(item) ?? 0) + 1), new Map())].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0], "pt-BR")); }
function List({ title, intro, items, icon: Icon }: { title: string; intro: string; items: { name: string; frequency: number; detail: string }[]; icon: typeof CheckCircle2 }) { return <article className="rounded-2xl border border-line bg-white p-5 shadow-sm"><h2 className="text-xl font-semibold">{title}</h2><p className="mt-1 text-sm text-muted">{intro}</p>{items.length ? <ul className="mt-4 space-y-3">{items.map((item) => <li key={item.name} className="flex gap-3 rounded-xl bg-neutral-100 p-3"><Icon className="mt-0.5 shrink-0" size={18} /><div><p className="text-sm font-semibold">{item.name} · {item.frequency} {item.frequency === 1 ? "registro" : "registros"}</p><p className="mt-1 text-xs leading-5 text-muted">{item.detail}</p></div></li>)}</ul> : <p className="mt-4 text-sm text-muted">Ainda não há análises suficientes para esta lista.</p>}</article>; }
