import { Check, ChevronDown, ChevronUp, RotateCcw } from "lucide-react";
import { useState } from "react";
import type { TrainingActivity } from "./training";
import { activityTypeLabels, priorityLabels } from "./training";

export function StudyDayCard({ activity, onToggle }: { activity: TrainingActivity; onToggle: () => void }) {
  const [expanded, setExpanded] = useState(false);
  return <article className={`rounded-2xl border bg-white p-4 shadow-sm ${activity.completedAt ? "border-green-200" : "border-line"}`}><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-bold uppercase tracking-wide text-muted">{activity.day}</span><span className="rounded-full bg-neutral-100 px-2.5 py-1 text-xs font-semibold">{activityTypeLabels[activity.type]}</span><span className="rounded-full border border-line px-2.5 py-1 text-xs font-semibold">Prioridade {priorityLabels[activity.priority].toLowerCase()}</span></div><h3 className="mt-2 font-semibold">{activity.title}</h3><p className="mt-1 text-sm text-muted">{activity.topicTitle} · {activity.estimatedMinutes} min</p></div><button type="button" onClick={onToggle} className={`inline-flex min-h-11 items-center justify-center gap-2 rounded-xl px-3 py-2 text-sm font-semibold focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-focus ${activity.completedAt ? "border border-line bg-white" : "bg-neutral-950 text-white"}`}>{activity.completedAt ? <RotateCcw size={16} /> : <Check size={16} />}{activity.completedAt ? "Desfazer" : "Concluir"}</button></div><button type="button" onClick={() => setExpanded((value) => !value)} aria-expanded={expanded} className="mt-3 inline-flex items-center gap-2 text-sm font-semibold underline-offset-4 hover:underline focus-visible:outline-2 focus-visible:outline-offset-2">{expanded ? <ChevronUp size={16} /> : <ChevronDown size={16} />}Detalhes</button>{expanded && <div className="mt-3 rounded-xl bg-neutral-100 p-3 text-sm leading-6"><strong>Motivo:</strong> {activity.reason}{activity.completedAt && <p className="mt-1 text-green-800">Concluída em {new Date(activity.completedAt).toLocaleString("pt-BR")}.</p>}</div>}</article>;
}
