"use client";
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ChartNoAxesCombined } from "lucide-react";
import type { CompletionEntry, TrainingActivity, TrainingExercise } from "./training";

export function TrainingProgress({ activities, exercises, topicProgress, history }: { activities: TrainingActivity[]; exercises: TrainingExercise[]; topicProgress: Record<string, number>; history: CompletionEntry[] }) {
  const completedActivities = activities.filter((item) => item.completedAt).length;
  const completedExercises = history.filter((item) => item.kind === "exercise").length;
  if (!history.length) return <section className="rounded-2xl border border-dashed border-line-strong bg-white px-6 py-14 text-center"><ChartNoAxesCombined className="mx-auto text-neutral-400" size={38} /><h2 className="mt-4 text-lg font-semibold">Seu progresso começa na primeira conclusão</h2><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-muted">Conclua uma atividade ou exercício para preencher os gráficos e o histórico recente.</p></section>;
  const topicData = exercises.map((exercise) => ({ name: exercise.topicTitle.length > 18 ? `${exercise.topicTitle.slice(0, 18)}…` : exercise.topicTitle, progress: topicProgress[exercise.topicId] ?? 0 })).slice(0, 6);
  const byDay = [...history].reverse().reduce<Map<string, number>>((map, item) => { const day = new Date(item.completedAt).toLocaleDateString("pt-BR", { day: "2-digit", month: "2-digit" }); return map.set(day, (map.get(day) ?? 0) + 1); }, new Map());
  const dayData = [...byDay].map(([day, total]) => ({ day, total }));
  const activityMinutes = history.filter((item) => item.kind === "activity").reduce((sum, item) => sum + item.minutes, 0); const exerciseMinutes = history.filter((item) => item.kind === "exercise").reduce((sum, item) => sum + item.minutes, 0);
  return <section aria-labelledby="training-progress-title"><h2 id="training-progress-title" className="text-xl font-semibold">Progresso do treinamento</h2><div className="mt-4 grid gap-4 sm:grid-cols-3"><Metric label="Progresso semanal" value={`${activities.length ? Math.round(completedActivities / activities.length * 100) : 0}%`} /><Metric label="Atividades concluídas" value={completedActivities} /><Metric label="Exercícios concluídos" value={completedExercises} /></div><div className="mt-4 grid gap-4 xl:grid-cols-2"><Chart title="Progresso por tema"><ResponsiveContainer width="100%" height={280}><BarChart data={topicData} margin={{ left: 0, right: 10 }}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="name" tick={{ fontSize: 11 }} /><YAxis domain={[0, 100]} /><Tooltip /><Bar dataKey="progress" name="Progresso (%)" fill="#171717" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer></Chart><Chart title="Conclusões por dia"><ResponsiveContainer width="100%" height={280}><LineChart data={dayData}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="day" /><YAxis allowDecimals={false} /><Tooltip /><Line type="monotone" dataKey="total" name="Conclusões" stroke="#15803d" strokeWidth={3} /></LineChart></ResponsiveContainer></Chart></div><div className="mt-4 grid gap-4 lg:grid-cols-2"><article className="rounded-2xl border border-line bg-white p-5"><h3 className="font-semibold">Distribuição do tempo estudado</h3><p className="mt-3 text-sm">Plano: <strong>{activityMinutes} min</strong></p><p className="mt-2 text-sm">Exercícios: <strong>{exerciseMinutes} min</strong></p></article><article className="rounded-2xl border border-line bg-white p-5"><h3 className="font-semibold">Histórico recente</h3><ul className="mt-3 space-y-2">{history.slice(0, 6).map((item) => <li key={item.id} className="border-b border-line pb-2 text-sm"><strong>{item.title}</strong><span className="mt-1 block text-xs text-muted">{new Date(item.completedAt).toLocaleString("pt-BR")} · {item.minutes} min</span></li>)}</ul></article></div></section>;
}
function Metric({ label, value }: { label: string; value: string | number }) { return <article className="rounded-2xl border border-line bg-white p-4"><p className="text-xs font-semibold uppercase text-muted">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></article>; }
function Chart({ title, children }: { title: string; children: React.ReactNode }) { return <article className="min-w-0 rounded-2xl border border-line bg-white p-4"><h3 className="mb-4 font-semibold">{title}</h3>{children}</article>; }
