import Link from "next/link";
import { Check, ExternalLink, Plus } from "lucide-react";
import type { ChessGame } from "@/lib/types/chess";
import type { TopicRecommendation } from "./training";
import { categoryLabels, levelLabels, priorityLabels } from "./training";

export function TrainingTopicCard({ topic, added, relatedGame, onAdd }: { topic: TopicRecommendation; added: boolean; relatedGame?: ChessGame; onAdd: () => void }) {
  return <article className="flex flex-col rounded-2xl border border-line bg-white p-5 shadow-sm"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-neutral-100 px-2.5 py-1 text-xs font-semibold">{categoryLabels[topic.category]}</span><span className="rounded-full border border-line px-2.5 py-1 text-xs font-semibold">{levelLabels[topic.level]}</span><span className="rounded-full border border-amber-200 bg-amber-50 px-2.5 py-1 text-xs font-semibold text-amber-900">Prioridade {priorityLabels[topic.priority].toLowerCase()}</span></div><h3 className="mt-3 text-lg font-semibold">{topic.title}</h3><p className="mt-2 text-sm leading-6 text-muted">{topic.description}</p><p className="mt-3 rounded-xl bg-neutral-100 p-3 text-sm leading-6">{topic.reason}{topic.fallback && <span className="block mt-1 font-semibold">Fallback simulado por falta de análises suficientes.</span>}</p><dl className="mt-4 grid grid-cols-3 gap-2 text-sm"><div><dt className="text-xs text-muted">Tempo</dt><dd className="font-semibold">{topic.estimatedMinutes} min</dd></div><div><dt className="text-xs text-muted">Frequência</dt><dd className="font-semibold">{topic.frequency}</dd></div><div><dt className="text-xs text-muted">Progresso</dt><dd className="font-semibold">{topic.progress}%</dd></div></dl>{relatedGame && <div className="mt-4 text-sm"><span className="text-muted">Recomendado após: </span><Link className="font-semibold underline" href={`/partidas/${relatedGame.id}`}>{relatedGame.title}</Link><Link href={`/partidas/${relatedGame.id}/analise`} aria-label={`Abrir análise de ${relatedGame.title}`} className="ml-2 inline-flex"><ExternalLink size={15} /></Link></div>}<div className="mt-auto flex flex-wrap gap-2 pt-5"><button type="button" disabled={added} onClick={onAdd} className="inline-flex min-h-11 flex-1 items-center justify-center gap-2 rounded-xl bg-neutral-950 px-3 py-2 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:bg-neutral-300 disabled:text-neutral-700">{added ? <Check size={16} /> : <Plus size={16} />}{added ? "Já adicionado" : "Adicionar ao plano"}</button><a href={`#details-${topic.id}`} className="inline-flex min-h-11 items-center rounded-xl border border-line px-3 py-2 text-sm font-semibold">Ver detalhes</a></div><span id={`details-${topic.id}`} className="sr-only">{topic.reason}</span></article>;
}
