import { create } from "zustand";
import { createJSONStorage, persist } from "zustand/middleware";
import { getSafeStorage, STORAGE_KEYS } from "@/lib/storage/storage";
import type { LessonBooking } from "@/lib/types/humanTeachers";

interface LessonBookingStore { bookings: LessonBooking[]; selectedTeacherId: string | null; hydrated: boolean; selectTeacher: (id: string | null) => void; addBooking: (booking: LessonBooking) => void; cancelBooking: (id: string) => void; resetBookings: () => void; }
const isRecord = (value: unknown): value is Record<string, unknown> => typeof value === "object" && value !== null;
const migrateBookings = (value: unknown): Pick<LessonBookingStore, "bookings" | "selectedTeacherId"> => { if (!isRecord(value)) return { bookings: [], selectedTeacherId: null }; return { bookings: Array.isArray(value.bookings) ? value.bookings.filter(isRecord).filter((item): item is Record<string, unknown> & LessonBooking => typeof item.id === "string" && typeof item.teacherId === "string") : [], selectedTeacherId: typeof value.selectedTeacherId === "string" ? value.selectedTeacherId : null }; };
export const useLessonBookingStore = create<LessonBookingStore>()(persist((set) => ({ bookings: [], selectedTeacherId: null, hydrated: false, selectTeacher: (selectedTeacherId) => set({ selectedTeacherId }), addBooking: (booking) => set((state) => ({ bookings: [booking, ...state.bookings] })), cancelBooking: (id) => set((state) => ({ bookings: state.bookings.map((booking) => booking.id === id ? { ...booking, status: "Cancelado localmente" } : booking) })), resetBookings: () => set({ bookings: [], selectedTeacherId: null }) }), { name: STORAGE_KEYS.lessonBookings, version: 1, storage: createJSONStorage(getSafeStorage), skipHydration: true, partialize: ({ bookings, selectedTeacherId }) => ({ bookings, selectedTeacherId }), migrate: migrateBookings, onRehydrateStorage: () => () => useLessonBookingStore.setState({ hydrated: true }) }));
export const hydrateLessonBookingStore = async (): Promise<void> => { await useLessonBookingStore.persist.rehydrate(); useLessonBookingStore.setState({ hydrated: true }); };
