import { BookOpenCheck, BrainCircuit, Camera, ChartNoAxesCombined, GraduationCap, MessageSquareText, ScanSearch, Users } from "lucide-react";
const items = [
  ["Análise didática de partidas", "Explicar decisões e momentos críticos sem esconder a fonte técnica.", "PGN, análise técnica e nível", "Transformar revisão em aprendizado", "Protótipo de interface", BookOpenCheck],
  ["Explicação de posições", "Organizar planos, candidatos e perguntas de revisão.", "FEN validado e contexto", "Entender ideias antes de decorar lances", "Planejado", ScanSearch],
  ["Reconhecimento de tabuleiro por imagem", "Converter uma imagem em posição revisável pelo usuário.", "Imagem privada e orientação", "Estudar posições do tabuleiro físico", "Dependência futura", Camera],
  ["Professor conversacional", "Responder dúvidas com linguagem adequada ao nível do jogador.", "Pergunta, contexto e fontes", "Tornar conceitos técnicos acessíveis", "Protótipo de interface", MessageSquareText],
  ["Identificação de padrões recorrentes", "Agrupar categorias observadas em várias partidas.", "Histórico autorizado e análises", "Priorizar erros frequentes", "Planejado", ChartNoAxesCombined],
  ["Plano de estudo adaptativo", "Ajustar temas conforme progresso e recorrência.", "Metas, progresso e padrões", "Usar melhor o tempo de estudo", "Planejado", BrainCircuit],
  ["Preparação para adversários", "Organizar material permitido para uma preparação privada.", "Partidas públicas/autorizadas", "Planejar estudo pré-partida", "Dependência futura", Users],
  ["Suporte ao professor humano", "Facilitar revisão, comentários e acompanhamento privados.", "Consentimento, posição e notas", "Combinar tecnologia e orientação humana", "Planejado", GraduationCap],
] as const;
export function AiCapabilities() { return <div className="space-y-6"><header><h2 className="text-2xl font-semibold">Capacidades futuras</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-muted">Possibilidades planejadas — nenhuma delas representa uma capacidade técnica ativa nesta versão.</p></header><div className="grid gap-4 md:grid-cols-2">{items.map(([name, description, data, benefit, status, Icon]) => <article key={name} className="rounded-2xl border border-line bg-white p-5"><span className="flex size-10 items-center justify-center rounded-xl bg-neutral-950 text-white"><Icon size={19} aria-hidden="true" /></span><div className="mt-4 flex flex-wrap items-start justify-between gap-2"><h3 className="font-semibold">{name}</h3><span className="rounded-full border border-line bg-neutral-100 px-2.5 py-1 text-xs font-bold">{status}</span></div><p className="mt-2 text-sm leading-6 text-muted">{description}</p><dl className="mt-4 space-y-2 border-t border-line pt-4 text-sm"><div><dt className="font-semibold">Dados necessários</dt><dd className="text-muted">{data}</dd></div><div><dt className="font-semibold">Benefício</dt><dd className="text-muted">{benefit}</dd></div></dl></article>)}</div></div>; }
