import { FileSearch, ImageIcon, LockKeyhole } from "lucide-react";
import { AnalysisStatusBadge } from "@/components/games/AnalysisStatusBadge";
import { OriginBadge } from "@/components/games/OriginBadge";
import type { ChessGame, GameAnalysis, UploadedPosition } from "@/lib/types/chess";
import type { FutureAiContextRef, FutureAiContextType } from "@/lib/future-ai/demo";
import { contextTypeLabels, errorCategoryLabels } from "@/lib/future-ai/demo";

const types: { id: FutureAiContextType; icon: typeof FileSearch }[] = [{ id: "game-analysis", icon: FileSearch }, { id: "saved-position", icon: ImageIcon }];
const resultLabels = { win: "Vitória", loss: "Derrota", draw: "Empate" } as const;

export function ContextSelector({ selected, games, analyses, positions, onSelect }: { selected: FutureAiContextRef | null; games: ChessGame[]; analyses: GameAnalysis[]; positions: UploadedPosition[]; onSelect: (context: FutureAiContextRef) => void }) {
  const type = selected?.type ?? null;
  const empty = type === "game-analysis" ? games.length === 0 : type === "saved-position" ? positions.length === 0 : false;
  return <section aria-labelledby="context-title" className="rounded-2xl border border-line bg-white p-5 shadow-sm"><h2 id="context-title" className="text-lg font-semibold">1. Escolha um contexto</h2><p className="mt-1 text-sm leading-6 text-muted">Use uma análise de partida ou uma posição privada enviada por imagem.</p><div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-1">{types.map(({ id, icon: Icon }) => <button key={id} type="button" aria-pressed={type === id} onClick={() => onSelect({ type: id, id: null, label: contextTypeLabels[id] })} className={`flex min-h-11 items-center gap-3 rounded-xl border px-3 py-2.5 text-left text-sm font-semibold focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-focus ${type === id ? "border-neutral-950 bg-neutral-950 text-white" : "border-line hover:bg-neutral-50"}`}><Icon size={17} aria-hidden="true" />{contextTypeLabels[id]}</button>)}</div>{!selected && <div className="mt-4 rounded-xl border border-dashed border-line-strong bg-neutral-50 p-5 text-center text-sm text-muted">Selecione um dos dois contextos para continuar.</div>}{empty && <div role="status" className="mt-4 rounded-xl border border-dashed border-line-strong p-5 text-center"><p className="font-semibold">Dados indisponíveis</p><p className="mt-1 text-sm text-muted">Não há itens privados nesta categoria.</p></div>}<div className="mt-4 max-h-[32rem] space-y-2 overflow-y-auto">
    {type === "game-analysis" && games.map((game) => { const analysis = analyses.find((item) => item.gameId === game.id); return <button key={game.id} type="button" aria-pressed={selected?.id === game.id} onClick={() => onSelect({ type: "game-analysis", id: game.id, label: `Análise · ${game.title}` })} className={`w-full rounded-xl border p-3 text-left focus-visible:outline-2 focus-visible:outline-focus ${selected?.id === game.id ? "border-neutral-950 bg-neutral-100" : "border-line"}`}><span className="font-semibold">{game.title}</span><span className="mt-2 flex flex-wrap gap-2"><OriginBadge origin={game.origin} /><span className="rounded-full border border-line px-2.5 py-1 text-xs font-semibold">{resultLabels[game.result]}</span><AnalysisStatusBadge status={analysis ? "analyzed" : game.analysisStatus} /></span><span className="mt-2 block text-xs leading-5 text-muted">vs. {game.opponent} · {new Date(`${game.date}T12:00:00`).toLocaleDateString("pt-BR")}</span>{analysis ? <span className="mt-2 flex flex-wrap gap-1">{analysis.errorCategories.map((category) => <span key={category} className="rounded-full bg-neutral-100 px-2 py-1 text-xs font-semibold">{errorCategoryLabels[category]}</span>)}</span> : <span className="mt-2 block text-xs text-muted">Fallback demonstrativo, sem avaliação técnica.</span>}</button>; })}
    {type === "saved-position" && positions.map((position) => <button key={position.id} type="button" aria-pressed={selected?.id === position.id} onClick={() => onSelect({ type: "saved-position", id: position.id, label: position.title })} className={`w-full rounded-xl border p-3 text-left focus-visible:outline-2 focus-visible:outline-focus ${selected?.id === position.id ? "border-neutral-950 bg-neutral-100" : "border-line"}`}><span className="font-semibold">{position.title}</span><span className="mt-2 flex flex-wrap gap-2"><span className="inline-flex items-center gap-1 rounded-full bg-neutral-950 px-2.5 py-1 text-xs font-semibold text-white"><LockKeyhole size={12} />Privada</span><span className="rounded-full border border-line px-2.5 py-1 text-xs font-semibold">{position.simulatedDetectedFen ? "FEN demonstrativo disponível" : "Sem FEN demonstrativo"}</span></span><span className="mt-2 block text-xs leading-5 text-muted">{position.imageOrigin === "physical_board_photo" ? "Foto de tabuleiro" : "Print de partida online"} · {position.description || "Sem contexto informado"}</span><span className="mt-1 block text-xs font-medium text-muted">O FEN é simulado e não foi extraído realmente da imagem.</span></button>)}
  </div></section>;
}
