import { ImageIcon, MessagesSquare, Swords, Target, FileSearch, LockKeyhole } from "lucide-react";
import { AnalysisStatusBadge } from "@/components/games/AnalysisStatusBadge";
import { OriginBadge } from "@/components/games/OriginBadge";
import type { ChessGame, GameAnalysis, TrainingTopic, UploadedPosition } from "@/lib/types/chess";
import type { FutureAiContextRef, FutureAiContextType } from "@/lib/future-ai/demo";
import { contextTypeLabels, errorCategoryLabels } from "@/lib/future-ai/demo";

const types: { id: FutureAiContextType; icon: typeof Swords }[] = [{ id: "game", icon: Swords }, { id: "analysis", icon: FileSearch }, { id: "position", icon: ImageIcon }, { id: "training", icon: Target }, { id: "none", icon: MessagesSquare }];
const resultLabels = { win: "Vitória", loss: "Derrota", draw: "Empate" } as const;
export function ContextSelector({ selected, games, analyses, positions, topics, progress, onSelect }: { selected: FutureAiContextRef | null; games: ChessGame[]; analyses: GameAnalysis[]; positions: UploadedPosition[]; topics: TrainingTopic[]; progress: Record<string, number>; onSelect: (context: FutureAiContextRef) => void }) {
  const type = selected?.type ?? null;
  const chooseType = (next: FutureAiContextType) => { if (next === "none") onSelect({ type: "none", id: null, label: contextTypeLabels.none }); else onSelect({ type: next, id: null, label: contextTypeLabels[next] }); };
  const empty = type === "game" ? games.length === 0 : type === "analysis" ? analyses.length === 0 : type === "position" ? positions.length === 0 : type === "training" ? topics.length === 0 : false;
  return <section aria-labelledby="context-title" className="rounded-2xl border border-line bg-white p-5 shadow-sm"><h2 id="context-title" className="text-lg font-semibold">1. Escolha um contexto</h2><p className="mt-1 text-sm leading-6 text-muted">A demonstração usa apenas dados privados ou visíveis do usuário atual.</p><div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-1">{types.map(({ id, icon: Icon }) => <button key={id} type="button" aria-pressed={type === id} onClick={() => chooseType(id)} className={`flex min-h-11 items-center gap-3 rounded-xl border px-3 py-2.5 text-left text-sm font-semibold focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-focus ${type === id ? "border-neutral-950 bg-neutral-950 text-white" : "border-line hover:bg-neutral-50"}`}><Icon size={17} aria-hidden="true" />{contextTypeLabels[id]}</button>)}</div>{!selected && <div className="mt-4 rounded-xl border border-dashed border-line-strong bg-neutral-50 p-5 text-center text-sm text-muted">Nenhum contexto selecionado. Escolha uma categoria para continuar.</div>}{selected?.type === "none" && <div className="mt-4 rounded-xl bg-neutral-100 p-4 text-sm leading-6">A conversa usará somente orientações gerais de estudo, sem afirmar conclusões sobre partidas ou posições.</div>}{empty && <div role="status" className="mt-4 rounded-xl border border-dashed border-line-strong p-5 text-center"><p className="font-semibold">Dados indisponíveis</p><p className="mt-1 text-sm text-muted">Não há itens visíveis nesta categoria. Escolha outro contexto.</p></div>}<div className="mt-4 max-h-[32rem] space-y-2 overflow-y-auto">
    {type === "game" && games.map((game) => <button key={game.id} type="button" aria-pressed={selected?.id === game.id} onClick={() => onSelect({ type: "game", id: game.id, label: game.title })} className={`w-full rounded-xl border p-3 text-left focus-visible:outline-2 focus-visible:outline-focus ${selected?.id === game.id ? "border-neutral-950 bg-neutral-100" : "border-line"}`}><span className="font-semibold">{game.title}</span><span className="mt-2 flex flex-wrap gap-2"><OriginBadge origin={game.origin} /><span className="rounded-full border border-line px-2.5 py-1 text-xs font-semibold">{resultLabels[game.result]}</span></span><span className="mt-2 block text-xs leading-5 text-muted">vs. {game.opponent} · {new Date(`${game.date}T12:00:00`).toLocaleDateString("pt-BR")}</span></button>)}
    {type === "analysis" && analyses.map((analysis) => { const game = games.find((item) => item.id === analysis.gameId); if (!game) return null; return <button key={analysis.id} type="button" aria-pressed={selected?.id === analysis.id} onClick={() => onSelect({ type: "analysis", id: analysis.id, label: `Análise · ${game.title}` })} className={`w-full rounded-xl border p-3 text-left focus-visible:outline-2 focus-visible:outline-focus ${selected?.id === analysis.id ? "border-neutral-950 bg-neutral-100" : "border-line"}`}><span className="font-semibold">{game.title}</span><span className="mt-2 flex flex-wrap gap-2"><AnalysisStatusBadge status="analyzed" />{analysis.errorCategories.map((category) => <span key={category} className="rounded-full bg-neutral-100 px-2.5 py-1 text-xs font-semibold">{errorCategoryLabels[category]}</span>)}</span></button>; })}
    {type === "position" && positions.map((position) => <button key={position.id} type="button" aria-pressed={selected?.id === position.id} onClick={() => onSelect({ type: "position", id: position.id, label: position.title })} className={`w-full rounded-xl border p-3 text-left focus-visible:outline-2 focus-visible:outline-focus ${selected?.id === position.id ? "border-neutral-950 bg-neutral-100" : "border-line"}`}><span className="font-semibold">{position.title}</span><span className="mt-2 flex flex-wrap gap-2"><span className="inline-flex items-center gap-1 rounded-full bg-neutral-950 px-2.5 py-1 text-xs font-semibold text-white"><LockKeyhole size={12} />Privada</span><span className="rounded-full border border-line px-2.5 py-1 text-xs font-semibold">{position.simulatedDetectedFen ? "Reconhecimento demonstrativo" : "Sem FEN demonstrativo"}</span></span><span className="mt-2 block text-xs text-muted">{position.imageOrigin === "physical_board_photo" ? "Foto de tabuleiro" : "Print de partida online"}</span></button>)}
    {type === "training" && topics.map((topic) => { const value = Number.isFinite(progress[topic.id]) ? progress[topic.id] : topic.progress; return <button key={topic.id} type="button" aria-pressed={selected?.id === topic.id} onClick={() => onSelect({ type: "training", id: topic.id, label: topic.title })} className={`w-full rounded-xl border p-3 text-left focus-visible:outline-2 focus-visible:outline-focus ${selected?.id === topic.id ? "border-neutral-950 bg-neutral-100" : "border-line"}`}><span className="font-semibold">{topic.title}</span><span className="mt-2 block text-xs text-muted">Prioridade {value < 40 ? "alta" : value < 80 ? "média" : "de revisão"} · {value >= 0 ? `${value}% concluído` : "Sem progresso"}</span></button>; })}
  </div></section>;
}
