import { Check, CircleDashed } from "lucide-react";
const phases = [
  ["Etapa atual", ["Interface", "Navegação", "Dados mockados", "Análises simuladas", "Persistência local"]],
  ["Próxima fase", ["Backend", "Autenticação", "Banco de dados", "Armazenamento seguro", "Partidas reais", "Comunicação em tempo real"]],
  ["Integração técnica futura", ["Motor de xadrez", "Visão computacional", "Recuperação de contexto", "LLM", "Monitoramento de qualidade", "Avaliações de segurança"]],
  ["Produto futuro", ["Professor personalizado", "Professor humano", "Aplicativo mobile", "Notificações", "Assinaturas ou planos como possibilidade"]],
] as const;
export function FutureRoadmap() { return <div className="space-y-6"><header><h2 className="text-2xl font-semibold">Roadmap conceitual</h2><p className="mt-2 text-sm leading-6 text-muted">Sequência de possibilidades sem datas de lançamento ou compromissos de entrega.</p></header><ol className="grid gap-4 lg:grid-cols-4">{phases.map(([phase, items], index) => <li key={phase} className="rounded-2xl border border-line bg-white p-5"><span className={`flex size-10 items-center justify-center rounded-full ${index === 0 ? "bg-neutral-950 text-white" : "bg-neutral-100"}`}>{index === 0 ? <Check size={19} /> : <CircleDashed size={19} />}</span><p className="mt-4 text-xs font-bold uppercase tracking-wider text-muted">Etapa {index + 1}</p><h3 className="mt-1 font-semibold">{phase}</h3><ul className="mt-4 space-y-2 text-sm text-muted">{items.map((item) => <li key={item}>— {item}</li>)}</ul></li>)}</ol><HumanTeacherIntegration /></div>; }
export function HumanTeacherIntegration() { const showMessage = (event: React.MouseEvent<HTMLButtonElement>) => { const target = event.currentTarget.parentElement?.querySelector<HTMLElement>("[role=status]"); if (target) target.textContent = "Recurso planejado para uma etapa futura."; }; return <section aria-labelledby="human-teacher-title" className="rounded-2xl border border-line bg-white p-5"><h3 id="human-teacher-title" className="text-xl font-semibold">Professor humano + tecnologia</h3><p className="mt-2 text-sm leading-6 text-muted">Uma futura área privada poderá apoiar o trabalho do professor, sem substituí-lo.</p><ul className="mt-4 grid gap-2 text-sm sm:grid-cols-2">{["Compartilhar uma posição de forma privada", "Solicitar revisão", "Anexar comentários", "Acompanhar correções", "Comparar explicações", "Agendar aula"].map((item) => <li key={item} className="rounded-xl bg-neutral-100 p-3">{item}</li>)}</ul><div className="mt-4 flex flex-wrap items-center gap-3"><button type="button" onClick={showMessage} className="min-h-11 rounded-xl bg-neutral-950 px-4 py-2.5 text-sm font-semibold text-white">Solicitar revisão futura</button><button type="button" onClick={showMessage} className="min-h-11 rounded-xl border border-line px-4 py-2.5 text-sm font-semibold">Agendar aula futura</button><p role="status" aria-live="polite" className="text-sm font-semibold text-muted"></p></div><p className="mt-4 text-xs leading-5 text-muted">Não há compartilhamento, mensagens, pagamentos, calendário ou videochamada reais.</p></section>; }
