import { Database, Eye, Gauge, MessageSquareText, Server, ShieldCheck } from "lucide-react";
const steps = ["Entrada do usuário", "Validação de acesso e privacidade", "Preparação dos dados da partida ou posição", "Motor de xadrez futuro para avaliações técnicas", "Recuperação do histórico e dos padrões do jogador", "LLM futuro para explicação didática", "Validação e rastreabilidade da resposta", "Apresentação ao jogador"];
const responsibilities = [
  ["Motor de xadrez futuro", Gauge, ["Movimentos legais", "Avaliação", "Melhores alternativas", "Erros técnicos", "Variantes"]],
  ["Modelo de linguagem futuro", MessageSquareText, ["Explicação", "Adaptação ao nível", "Organização do estudo", "Linguagem natural", "Diálogo"]],
  ["Visão computacional futura", Eye, ["Detectar tabuleiro", "Identificar peças", "Estimar orientação", "Gerar posição para revisão"]],
  ["Backend futuro", Server, ["Permissões", "Privacidade", "Autenticação", "Persistência", "Auditoria", "Histórico", "Segurança"]],
] as const;
export function FutureArchitecture() { return <div className="space-y-8"><header><h2 className="text-2xl font-semibold">Como funcionará</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-muted">Arquitetura conceitual. Nenhuma etapa técnica futura está conectada ao protótipo.</p></header><section aria-labelledby="future-flow-title" className="rounded-2xl border border-line bg-white p-5"><h3 id="future-flow-title" className="text-lg font-semibold">Fluxo técnico futuro</h3><div className="mt-3 flex flex-wrap gap-2" aria-label="Entradas previstas">{["PGN", "FEN", "Imagem", "Partida da plataforma", "Pergunta em linguagem natural"].map((item) => <span key={item} className="rounded-full border border-line bg-neutral-100 px-3 py-1.5 text-xs font-bold">{item}</span>)}</div><ol className="mt-6 grid gap-3 md:grid-cols-2">{steps.map((step, index) => <li key={step} className="flex gap-3 rounded-xl border border-line p-4"><span className="flex size-7 shrink-0 items-center justify-center rounded-full bg-neutral-950 text-xs font-bold text-white">{index + 1}</span><span className="text-sm font-semibold leading-6">{step}</span></li>)}</ol><div className="mt-5 grid gap-3 sm:grid-cols-2"><p className="rounded-xl bg-neutral-100 p-4 text-sm leading-6"><Database className="mb-2" size={19} /><strong>Fontes separadas.</strong> Um motor como Stockfish ou equivalente faria a avaliação técnica; o LLM transformaria informações validadas em explicações.</p><p className="rounded-xl bg-neutral-100 p-4 text-sm leading-6"><ShieldCheck className="mb-2" size={19} /><strong>Limites verificáveis.</strong> Visão computacional reconheceria a imagem. O LLM não deveria inventar avaliações, e permissões reais dependeriam do backend.</p></div></section><section aria-labelledby="responsibility-title"><h3 id="responsibility-title" className="text-xl font-semibold">Separação de responsabilidades</h3><div className="mt-4 grid gap-4 md:grid-cols-2">{responsibilities.map(([name, Icon, list]) => <article key={name} className="rounded-2xl border border-line bg-white p-5"><Icon size={21} aria-hidden="true" /><h4 className="mt-3 font-semibold">{name}</h4><ul className="mt-3 list-disc space-y-1 pl-5 text-sm leading-6 text-muted">{list.map((item) => <li key={item}>{item}</li>)}</ul></article>)}</div></section><PrivacyAndSafety /></div>; }
export function PrivacyAndSafety() { return <section aria-labelledby="privacy-title" className="rounded-2xl border border-neutral-950 bg-neutral-950 p-5 text-white"><h3 id="privacy-title" className="text-xl font-semibold">Privacidade, segurança e rastreabilidade</h3><ul className="mt-4 grid gap-2 text-sm leading-6 text-neutral-200 md:grid-cols-2">{["Partidas externas permanecem privadas.", "Posições enviadas por imagem permanecem privadas.", "Observações pessoais não aparecem em perfis públicos.", "O histórico do professor é privado.", "Estatísticas públicas usam somente partidas da plataforma.", "Acesso deverá ser validado no backend.", "Respostas devem indicar fontes e dados utilizados.", "Avaliações técnicas devem vir do mecanismo apropriado.", "Conteúdo incerto deve ser identificado."].map((item) => <li key={item} className="flex gap-2"><span aria-hidden="true">—</span>{item}</li>)}</ul><p className="mt-5 rounded-xl bg-white p-4 text-sm font-semibold leading-6 text-neutral-950">Ocultar elementos na interface não representa segurança real. O produto final deverá validar todas as permissões no servidor.</p></section>; }
