"use client";
import { Chessboard } from "react-chessboard";
import { BadgeCheck, Sparkles } from "lucide-react";
import { isValidFen } from "./uploadForm";

export function FutureImageAnalysis({ fen }: { fen: string | null }) {
  const validFen = Boolean(fen && isValidFen(fen));
  return <section className="rounded-2xl border border-line bg-surface p-5 shadow-sm" aria-labelledby="future-analysis-title"><div className="flex items-start gap-3"><span className="rounded-xl bg-neutral-950 p-2 text-white"><Sparkles size={19}/></span><div><div className="flex flex-wrap items-center gap-2"><h2 id="future-analysis-title" className="text-lg font-semibold">Prévia da futura análise por imagem</h2><span className="rounded-full bg-neutral-200 px-2.5 py-1 text-xs font-bold uppercase tracking-wide">Simulado</span></div><p className="mt-1 text-sm leading-6 text-muted">Nenhum conteúdo desta demonstração foi extraído da imagem. Os exemplos abaixo representam apenas a experiência planejada para uma futura integração de visão computacional e IA.</p></div></div>
    {validFen ? <div className="mt-5 grid gap-5 lg:grid-cols-[minmax(240px,380px)_1fr]"><div><p className="mb-2 text-sm font-semibold">Posição do FEN informado manualmente</p><div className="overflow-hidden rounded-lg"><Chessboard options={{ id:`upload-board-${fen}`, position:fen!, allowDragging:false, allowDrawingArrows:false, showNotation:true, darkSquareStyle:{backgroundColor:"#525252"}, lightSquareStyle:{backgroundColor:"#f5f5f5"} }}/></div></div><div><p className="rounded-xl bg-neutral-100 p-4 text-sm leading-6"><strong>Comentário demonstrativo:</strong> a posição manual está pronta para uma futura explicação contextual. Nenhuma avaliação enxadrística foi calculada.</p><ul className="mt-4 space-y-2 text-sm">{["Reconhecimento das peças", "Conversão automática para FEN", "Identificação do lado a jogar", "Detecção de temas táticos", "Explicação da posição"].map((item)=><li key={item} className="flex items-center gap-2"><BadgeCheck size={16} className="text-neutral-600"/> {item} <span className="ml-auto text-xs font-bold text-muted">FUTURO · SIMULADO</span></li>)}</ul></div></div> : <div className="mt-5 rounded-xl border border-dashed border-line-strong bg-neutral-50 p-5"><p className="font-semibold">Nenhuma posição foi informada.</p><p className="mt-2 text-sm leading-6 text-muted">A futura análise dependerá do reconhecimento da imagem. Este protótipo não inventa uma posição nem exibe resultados falsos. Para ver o tabuleiro demonstrativo, informe um FEN manual válido em um novo envio.</p></div>}
  </section>;
}
