"use client";
import Link from "next/link";
import { Chessboard } from "react-chessboard";
import { BadgeCheck, ExternalLink, Sparkles } from "lucide-react";
import type { UploadedPosition } from "@/lib/types/chess";
import { simulatedRecognitionDisclaimer } from "./uploads";

export function FutureImageAnalysis({ upload }: { upload: UploadedPosition }) {
  return <section className="rounded-2xl border border-line bg-surface p-5 shadow-sm" aria-labelledby="future-analysis-title"><div className="flex items-start gap-3"><span className="rounded-xl bg-neutral-950 p-2 text-white"><Sparkles size={19}/></span><div><div className="flex flex-wrap items-center gap-2"><h2 id="future-analysis-title" className="text-lg font-semibold">Demonstração de reconhecimento</h2><span className="rounded-full bg-neutral-200 px-2.5 py-1 text-xs font-bold uppercase tracking-wide">Simulado</span></div><p className="mt-1 text-sm leading-6 text-muted">{simulatedRecognitionDisclaimer}</p></div></div>
    {upload.simulatedDetectedFen ? <div className="mt-5 grid gap-5 lg:grid-cols-[minmax(240px,380px)_1fr]"><div><p className="mb-2 text-sm font-semibold">Posição demonstrativa</p><div className="overflow-hidden rounded-lg"><Chessboard options={{ id: `upload-board-${upload.id}`, position: upload.simulatedDetectedFen, allowDragging: false, allowDrawingArrows: false, showNotation: true, darkSquareStyle: { backgroundColor: "#525252" }, lightSquareStyle: { backgroundColor: "#f5f5f5" } }}/></div></div><div><dl className="space-y-3 text-sm"><div><dt className="font-semibold">Lado a jogar</dt><dd className="text-muted">{upload.simulatedSideToMove === "black" ? "Pretas" : "Brancas"} · simulado</dd></div>{upload.simulatedConfidence !== null && <div><dt className="font-semibold">Confiança simulada da demonstração</dt><dd className="text-muted">{Math.round(upload.simulatedConfidence * 100)}%</dd></div>}</dl><ul className="mt-5 space-y-2 text-sm">{["Reconhecimento das peças", "Conversão automática para FEN", "Identificação do lado a jogar"].map((item) => <li key={item} className="flex items-center gap-2"><BadgeCheck size={16} className="text-neutral-600"/>{item}<span className="ml-auto text-xs font-bold text-muted">FUTURO · SIMULADO</span></li>)}</ul><Link href={`/estudo/posicoes/${upload.id}`} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-neutral-950 px-4 py-2.5 text-sm font-semibold text-white"><ExternalLink size={16}/>Abrir no tabuleiro</Link></div></div> : <div className="mt-5 rounded-xl border border-dashed border-line-strong bg-neutral-50 p-5"><p className="font-semibold">Nenhuma posição foi reconhecida.</p><p className="mt-2 text-sm leading-6 text-muted">O tabuleiro de estudo usará a posição inicial apenas como placeholder visual, sem afirmar que ela corresponde à imagem.</p><Link href={`/estudo/posicoes/${upload.id}`} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-neutral-950 px-4 py-2.5 text-sm font-semibold text-white"><ExternalLink size={16}/>Abrir no tabuleiro</Link></div>}
  </section>;
}
