"use client";
import Link from "next/link";
import { Eye, ExternalLink, FlaskConical, Lock, RotateCcw, Search, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";
import type { ImageOrigin, UploadedPosition } from "@/lib/types/chess";
import { imageOriginLabels, recognitionStatusLabels, sourceContextLabels } from "./uploads";

const normalize = (value: string) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
export function SavedUploads({ uploads, onDetails, onDemo, onDelete, onRestore }: { uploads: UploadedPosition[]; onDetails: (upload: UploadedPosition) => void; onDemo: (upload: UploadedPosition) => void; onDelete: (upload: UploadedPosition) => void; onRestore: () => void }) {
  const [query, setQuery] = useState(""); const [origin, setOrigin] = useState<ImageOrigin | "all">("all"); const [sort, setSort] = useState<"recent" | "oldest">("recent");
  const filtered = useMemo(() => uploads.filter((upload) => { const searchable = [upload.title, upload.description, imageOriginLabels[upload.imageOrigin], sourceContextLabels[upload.sourceContext], upload.sourceDetails, upload.personalStudyNotes, ...upload.tags].map(normalize).join(" "); return (!query || searchable.includes(normalize(query))) && (origin === "all" || upload.imageOrigin === origin); }).sort((a, b) => sort === "recent" ? b.date.localeCompare(a.date) : a.date.localeCompare(b.date)), [uploads, query, origin, sort]);
  return <div className="space-y-5"><div className="flex flex-col gap-3 rounded-2xl border border-line bg-white p-4 shadow-sm lg:flex-row"><label className="relative flex-1"><span className="sr-only">Buscar posições</span><Search className="absolute left-3 top-3 text-muted" size={17}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar por título, contexto, observações ou tags" className="w-full rounded-xl border border-line py-2.5 pl-10 pr-3 text-sm outline-none focus:ring-2 focus:ring-neutral-400"/></label><select aria-label="Filtrar por origem da imagem" value={origin} onChange={(event) => setOrigin(event.target.value as ImageOrigin | "all")} className="rounded-xl border border-line px-3 py-2.5 text-sm"><option value="all">Todas as origens</option>{Object.entries(imageOriginLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select aria-label="Ordenar posições" value={sort} onChange={(event) => setSort(event.target.value as "recent" | "oldest")} className="rounded-xl border border-line px-3 py-2.5 text-sm"><option value="recent">Data mais recente</option><option value="oldest">Data mais antiga</option></select><button type="button" onClick={onRestore} className="inline-flex items-center justify-center gap-2 rounded-xl border border-line px-4 py-2.5 text-sm font-semibold hover:bg-neutral-100"><RotateCcw size={16}/>Restaurar demonstração</button></div>
    {filtered.length === 0 ? <section className="rounded-2xl border border-dashed border-line-strong bg-white px-6 py-14 text-center"><Search className="mx-auto text-neutral-400" size={34}/><h2 className="mt-4 text-lg font-semibold">{uploads.length ? "Nenhuma posição encontrada" : "Nenhuma posição salva"}</h2><p className="mt-2 text-sm text-muted">{uploads.length ? "Ajuste a busca ou os filtros." : "Cadastre uma posição ou restaure os dados de demonstração."}</p></section> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map((upload) => <article key={upload.id} className="flex flex-col rounded-2xl border border-line bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><span className="inline-flex items-center gap-1 rounded-full bg-neutral-950 px-2.5 py-1 text-xs font-bold text-white"><Lock size={12}/>Privada</span><h2 className="mt-3 text-lg font-semibold">{upload.title}</h2><p className="mt-1 text-sm text-muted">{imageOriginLabels[upload.imageOrigin]}</p></div><span className="rounded-full bg-neutral-100 px-2.5 py-1 text-xs font-semibold">{recognitionStatusLabels[upload.recognitionStatus]}</span></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="font-semibold">Data</dt><dd className="text-muted">{new Date(`${upload.date}T12:00:00`).toLocaleDateString("pt-BR")}</dd></div><div><dt className="font-semibold">Contexto</dt><dd className="text-muted">{sourceContextLabels[upload.sourceContext]}{upload.sourceDetails ? ` — ${upload.sourceDetails}` : ""}</dd></div></dl><div className="mt-4 flex flex-wrap gap-1">{upload.tags.map((tag) => <span key={tag} className="rounded-full bg-neutral-100 px-2 py-1 text-xs">{tag}</span>)}</div>{upload.description && <p className="mt-4 text-sm text-muted">{upload.description}</p>}{upload.personalStudyNotes && <p className="mt-3 rounded-xl bg-neutral-50 p-3 text-xs leading-5 text-muted"><strong>Anotação:</strong> {upload.personalStudyNotes}</p>}<div className="mt-auto grid grid-cols-2 gap-2 pt-5"><button type="button" onClick={() => onDetails(upload)} className="inline-flex items-center justify-center gap-1 rounded-lg border border-line p-2 text-xs font-semibold hover:bg-neutral-100"><Eye size={14}/>Ver detalhes</button><button type="button" onClick={() => onDemo(upload)} className="inline-flex items-center justify-center gap-1 rounded-lg border border-line p-2 text-xs font-semibold hover:bg-neutral-100"><FlaskConical size={14}/>Ver demonstração</button><Link href={`/estudo/posicoes/${upload.id}`} className="inline-flex items-center justify-center gap-1 rounded-lg bg-neutral-950 p-2 text-xs font-semibold text-white"><ExternalLink size={14}/>Abrir no tabuleiro</Link><button type="button" onClick={() => onDelete(upload)} className="inline-flex items-center justify-center gap-1 rounded-lg border border-red-200 p-2 text-xs font-semibold text-red-700 hover:bg-red-50"><Trash2 size={14}/>Excluir</button></div></article>)}</div>}
  </div>;
}
