"use client";
import { useEffect, useState } from "react";
import { MockNotice } from "@/components/MockNotice";
import { PageTitle } from "@/components/PageTitle";
import { DeleteGameDialog } from "@/components/games/DeleteGameDialog";
import { mockGames } from "@/lib/data/games";
import { currentUser } from "@/lib/data/users";
import type { UploadedPosition } from "@/lib/types/chess";
import { hydrateUploadStore, useUploadStore } from "@/store/useUploadStore";
import { SavedUploads } from "./SavedUploads";
import { UploadDetailsDialog } from "./UploadDetailsDialog";
import { UploadForm } from "./UploadForm";
import type { PreviewFile } from "./UploadDropzone";
import type { UploadFormValues } from "./uploadForm";

export function UploadContent(){const uploads=useUploadStore(state=>state.uploads);const addUpload=useUploadStore(state=>state.addUpload);const deleteUpload=useUploadStore(state=>state.deleteUpload);const resetUploads=useUploadStore(state=>state.resetUploads);const [hydrated,setHydrated]=useState(false);const [tab,setTab]=useState<"new"|"saved">("new");const [message,setMessage]=useState("");const [selected,setSelected]=useState<UploadedPosition|null>(null);const [dialogMode,setDialogMode]=useState<"details"|"demo">("details");const [deleting,setDeleting]=useState<UploadedPosition|null>(null);const [restore,setRestore]=useState(false);useEffect(()=>{let active=true;void hydrateUploadStore().finally(()=>{if(active)setHydrated(true)});return()=>{active=false}},[]); const save=async(values:UploadFormValues,files:PreviewFile[])=>{await new Promise(resolve=>setTimeout(resolve,350));const now=new Date().toISOString();addUpload({id:crypto.randomUUID(),ownerUserId:currentUser.id,visibility:"private",title:values.title.trim(),uploadType:values.uploadType||"other",uploadTypeDetails:values.uploadTypeDetails.trim(),date:values.date,source:values.source||"outro",sourceDetails:values.sourceDetails.trim(),description:values.description.trim(),manualFen:values.manualFen.trim()||null,linkedGameId:values.linkedGameId||null,tags:values.tags,files:files.map(({file})=>({name:file.name,mimeType:file.type as "image/jpeg"|"image/png"|"image/webp",sizeInBytes:file.size})),imageCount:files.length,status:"metadata_saved",notes:values.description.trim(),createdAt:now,updatedAt:now});setMessage("Envio salvo com sucesso. Somente os metadados foram persistidos.");setTab("saved")}; if(!hydrated)return <div role="status" className="animate-pulse rounded-2xl border border-line bg-white p-8">Carregando envios…</div>;
 return <div className="space-y-7"><PageTitle eyebrow="Importação privada" title="Enviar Imagem" description="Organize imagens de posições e partidas sem processamento automático."/><MockNotice>O reconhecimento automático de tabuleiros e peças não está implementado. Nesta versão, a imagem é usada somente para demonstrar a interface e o fluxo futuro do produto.</MockNotice><div role="tablist" aria-label="Seções de envio" className="inline-flex rounded-xl border border-line bg-white p-1">{[["new","Novo envio"],["saved","Meus envios"]].map(([value,label])=><button key={value} role="tab" aria-selected={tab===value} type="button" onClick={()=>{setTab(value as "new"|"saved");setMessage("")}} className={`rounded-lg px-4 py-2.5 text-sm font-semibold focus-visible:outline-2 focus-visible:outline-offset-2 ${tab===value?"bg-neutral-950 text-white":"text-neutral-700 hover:bg-neutral-100"}`}>{label}</button>)}</div>{message&&<div role="status" aria-live="polite" className="rounded-xl border border-green-200 bg-green-50 px-4 py-3 text-sm font-medium text-green-800">{message}</div>}{tab==="new"?<UploadForm games={mockGames.filter(game=>game.ownerUserId===currentUser.id)} onSave={save}/>:<SavedUploads uploads={uploads.filter(upload=>upload.ownerUserId===currentUser.id)} onDetails={upload=>{setSelected(upload);setDialogMode("details")}} onDemo={upload=>{setSelected(upload);setDialogMode("demo")}} onDelete={setDeleting} onRestore={()=>setRestore(true)}/>}<UploadDetailsDialog upload={selected} mode={dialogMode} onClose={()=>setSelected(null)}/><DeleteGameDialog open={Boolean(deleting)} title="Excluir envio?" description={`O envio “${deleting?.title??"selecionado"}” será removido deste navegador. Esta ação não pode ser desfeita.`} confirmLabel="Excluir envio" destructive onCancel={()=>setDeleting(null)} onConfirm={()=>{if(deleting&&deleteUpload(deleting.id))setMessage(`Envio “${deleting.title}” excluído.`);setDeleting(null)}}/><DeleteGameDialog open={restore} title="Restaurar dados de demonstração?" description="Os envios atuais serão substituídos pelos dados simulados originais do TeaChess." confirmLabel="Restaurar dados" onCancel={()=>setRestore(false)} onConfirm={()=>{resetUploads();setRestore(false);setMessage("Dados de demonstração restaurados com sucesso.")}}/></div>}
