"use client";
/* eslint-disable @next/next/no-img-element -- object URLs temporários não passam pelo otimizador de imagens. */
import { ArrowDown, ArrowUp, ImagePlus, RefreshCw, Trash2 } from "lucide-react";
import { useEffect, useRef } from "react";
import { useDropzone, type FileRejection } from "react-dropzone";

export interface PreviewFile { id: string; file: File; previewUrl: string }
const formatBytes = (bytes: number) => bytes < 1024 * 1024 ? `${Math.round(bytes / 1024)} KB` : `${(bytes / 1024 / 1024).toFixed(1)} MB`;
const rejectionMessage = (rejections: FileRejection[]) => rejections.some(({ errors }) => errors.some((error) => error.code === "file-too-large")) ? "O arquivo excede o limite de 10 MB." : rejections.some(({ errors }) => errors.some((error) => error.code === "file-invalid-type")) ? "Formato inválido. Use PNG, JPEG ou WebP." : rejections.some(({ errors }) => errors.some((error) => error.code === "too-many-files")) ? "Quantidade inválida. Use no máximo 10 imagens na sequência." : "Não foi possível adicionar este arquivo.";

export function UploadDropzone({ files, sequence, error, onChange, onError }: { files: PreviewFile[]; sequence: boolean; error?: string; onChange: (files: PreviewFile[]) => void; onError: (message: string) => void }) {
  const filesRef = useRef(files); useEffect(() => { filesRef.current = files; }, [files]);
  useEffect(() => () => filesRef.current.forEach((item) => URL.revokeObjectURL(item.previewUrl)), []);
  const addFiles = (accepted: File[]) => { const additions = accepted.map((file) => ({ id: crypto.randomUUID(), file, previewUrl: URL.createObjectURL(file) })); if (!sequence && additions.length) { files.forEach((item) => URL.revokeObjectURL(item.previewUrl)); onChange([additions[0]]); } else onChange([...files, ...additions].slice(0, 10)); onError(""); };
  const { getRootProps, getInputProps, isDragActive, open } = useDropzone({ accept:{ "image/png":[".png"], "image/jpeg":[".jpg", ".jpeg"], "image/webp":[".webp"] }, maxSize:10 * 1024 * 1024, maxFiles:sequence ? 10 : 1, multiple:sequence, noClick:files.length > 0, onDropAccepted:addFiles, onDropRejected:(items) => onError(rejectionMessage(items)) });
  const remove = (id: string) => { const item = files.find((file) => file.id === id); if (item) URL.revokeObjectURL(item.previewUrl); onChange(files.filter((file) => file.id !== id)); };
  const move = (index: number, direction: -1 | 1) => { const next=[...files]; const target=index+direction; if (target < 0 || target >= next.length) return; [next[index], next[target]]=[next[target],next[index]]; onChange(next); };
  return <section aria-labelledby="upload-files-title"><div className="flex items-end justify-between gap-3"><div><h2 id="upload-files-title" className="text-lg font-semibold">Imagens</h2><p className="mt-1 text-sm text-muted">PNG, JPEG ou WebP, até 10 MB por arquivo.</p></div>{files.length > 0 && <button type="button" onClick={open} className="inline-flex items-center gap-2 rounded-xl border border-line px-3 py-2 text-sm font-semibold hover:bg-neutral-100 focus-visible:outline-2 focus-visible:outline-offset-2"><RefreshCw size={15}/>{sequence ? "Adicionar" : "Substituir"}</button>}</div>
    <div {...getRootProps({ role:"button", tabIndex:0, "aria-label":"Selecionar ou arrastar imagens", className:`mt-3 flex min-h-44 cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed p-6 text-center outline-none focus-visible:ring-2 focus-visible:ring-neutral-700 ${isDragActive ? "border-neutral-950 bg-neutral-100" : "border-line-strong bg-neutral-50"}` })}><input {...getInputProps()} /><ImagePlus size={32} className="text-neutral-500"/><p className="mt-3 font-semibold">{isDragActive ? "Solte as imagens aqui" : files.length ? "Arraste mais imagens aqui" : "Arraste imagens ou pressione para selecionar"}</p><p className="mt-1 text-sm text-muted">{sequence ? "Sequência: de 2 a 10 imagens" : "Posição única: 1 imagem"}</p></div>
    {error && <p role="alert" className="mt-2 text-sm font-medium text-red-700">{error}</p>}
    {files.length > 0 && <ol className="mt-4 grid gap-3 sm:grid-cols-2">{files.map((item,index)=><li key={item.id} className="overflow-hidden rounded-xl border border-line bg-white"><div className="relative aspect-video bg-neutral-100"><img src={item.previewUrl} alt={`Preview temporário de ${item.file.name}`} className="size-full object-contain"/>{sequence && <span className="absolute left-2 top-2 rounded-full bg-black px-2 py-1 text-xs font-bold text-white">{index+1}</span>}</div><div className="flex items-center gap-2 p-3"><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{item.file.name}</p><p className="text-xs text-muted">{item.file.type} · {formatBytes(item.file.size)}</p></div>{sequence && <><button type="button" disabled={index===0} onClick={()=>move(index,-1)} aria-label={`Mover ${item.file.name} para cima`} className="rounded-lg p-2 hover:bg-neutral-100 disabled:opacity-30"><ArrowUp size={16}/></button><button type="button" disabled={index===files.length-1} onClick={()=>move(index,1)} aria-label={`Mover ${item.file.name} para baixo`} className="rounded-lg p-2 hover:bg-neutral-100 disabled:opacity-30"><ArrowDown size={16}/></button></>}<button type="button" onClick={()=>remove(item.id)} aria-label={`Remover ${item.file.name}`} className="rounded-lg p-2 text-red-700 hover:bg-red-50"><Trash2 size={16}/></button></div></li>)}</ol>}
    {sequence && <p className="mt-3 rounded-xl bg-neutral-100 p-3 text-sm text-neutral-700">No futuro, a ordem poderá ajudar a reconstruir uma partida. Nenhum lance ou PGN é reconhecido nesta versão.</p>}
  </section>;
}
