"use client";
import Link from "next/link";
import { ExternalLink } from "lucide-react";
import { useEffect, useRef } from "react";
import type { UploadedPosition } from "@/lib/types/chess";
import { FutureImageAnalysis } from "./FutureImageAnalysis";
import { imageOriginLabels, recognitionStatusLabels, sourceContextLabels } from "./uploads";

export function UploadDetailsDialog({ upload, mode, onClose }: { upload: UploadedPosition | null; mode: "details" | "demo"; onClose: () => void }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { const dialog = ref.current; if (upload && !dialog?.open) dialog?.showModal(); if (!upload && dialog?.open) dialog.close(); }, [upload]);
  return <dialog ref={ref} onCancel={(event) => { event.preventDefault(); onClose(); }} onClose={onClose} aria-labelledby="upload-dialog-title" className="m-auto max-h-[90vh] w-[calc(100%-2rem)] max-w-3xl overflow-y-auto rounded-2xl border border-line bg-white p-0 shadow-2xl backdrop:bg-black/60">{upload && <><div className="border-b border-line p-5"><h2 id="upload-dialog-title" className="text-xl font-semibold">{mode === "demo" ? "Demonstração de reconhecimento" : upload.title}</h2><p className="mt-1 text-sm text-muted">Posição privada · somente metadados locais</p></div><div className="p-5">{mode === "demo" ? <FutureImageAnalysis upload={upload}/> : <div className="grid gap-4 text-sm sm:grid-cols-2"><Detail label="Origem da imagem" value={imageOriginLabels[upload.imageOrigin]}/><Detail label="Plataforma ou contexto" value={`${sourceContextLabels[upload.sourceContext]}${upload.sourceDetails ? ` — ${upload.sourceDetails}` : ""}`}/><Detail label="Data" value={new Date(`${upload.date}T12:00:00`).toLocaleDateString("pt-BR")}/><Detail label="Status demonstrativo" value={recognitionStatusLabels[upload.recognitionStatus]}/><Detail label="Descrição ou observações" value={upload.description || "Não informadas"}/><Detail label="Tags" value={upload.tags.join(", ") || "Nenhuma"}/><Detail label="Arquivo de referência" value={`${upload.fileName} · ${upload.mimeType} · ${(upload.fileSize / 1024 / 1024).toFixed(2)} MB`}/><Detail label="Favorita" value={upload.favorite ? "Sim" : "Não"}/>{upload.migrationNote && <div className="sm:col-span-2 rounded-xl bg-amber-50 p-4 text-amber-900">{upload.migrationNote}</div>}<div className="sm:col-span-2 rounded-xl bg-neutral-100 p-4 text-muted">A imagem original não está disponível após recarregar, pois este protótipo armazena somente os metadados.</div></div>}</div><div className="flex flex-wrap justify-end gap-2 border-t border-line bg-neutral-50 p-4"><Link href={`/estudo/posicoes/${upload.id}`} onClick={onClose} className="inline-flex items-center gap-2 rounded-xl bg-neutral-950 px-4 py-2.5 text-sm font-semibold text-white"><ExternalLink size={16}/>Abrir no tabuleiro</Link><button type="button" onClick={onClose} className="rounded-xl border border-line px-4 py-2.5 text-sm font-semibold">Fechar</button></div></>}</dialog>;
}
function Detail({ label, value }: { label: string; value: string }) { return <div><p className="font-semibold">{label}</p><p className="mt-1 break-words text-muted">{value}</p></div>; }
