"use client";
import { Save } from "lucide-react";
import { type FormEvent, useState } from "react";
import { TagInput } from "@/components/games/TagInput";
import { FormFieldError } from "@/components/games/FormFieldError";
import type { ChessGame, PositionSourceContext } from "@/lib/types/chess";
import { UploadDropzone, type PreviewImage } from "./UploadDropzone";
import { emptyUploadForm, validateUpload, type UploadFormErrors, type UploadFormValues } from "./uploadForm";
import { imageOriginLabels, onlineContextLabels, physicalContextLabels } from "./uploads";

const inputClass = "mt-2 w-full rounded-xl border border-line bg-white px-3.5 py-2.5 text-sm outline-none focus:border-neutral-700 focus:ring-2 focus:ring-neutral-300";
export function UploadForm({ games, onSave }: { games: ChessGame[]; onSave: (values: UploadFormValues, image: PreviewImage) => Promise<void> }) {
  const [values, setValues] = useState(emptyUploadForm);
  const [image, setImage] = useState<PreviewImage | null>(null);
  const [errors, setErrors] = useState<UploadFormErrors>({});
  const [dropError, setDropError] = useState("");
  const [saving, setSaving] = useState(false);
  const update = <K extends keyof UploadFormValues>(key: K, value: UploadFormValues[K]) => { setValues((current) => ({ ...current, [key]: value })); setErrors((current) => ({ ...current, [key]: undefined })); };
  const submit = async (event: FormEvent) => { event.preventDefault(); const next = validateUpload(values, Boolean(image)); setErrors(next); if (Object.keys(next).length || !image) { requestAnimationFrame(() => document.querySelector<HTMLElement>("[aria-invalid='true']")?.focus()); return; } setSaving(true); try { await onSave(values, image); setImage(null); setValues(emptyUploadForm()); setErrors({}); } finally { setSaving(false); } };
  const contexts = values.imageOrigin === "online_game_screenshot" ? onlineContextLabels : values.imageOrigin === "physical_board_photo" ? physicalContextLabels : null;
  return <form noValidate onSubmit={submit} className="space-y-6"><div className="grid gap-6 xl:grid-cols-[minmax(0,.9fr)_minmax(0,1.1fr)]"><div className="rounded-2xl border border-line bg-surface p-5 shadow-sm"><UploadDropzone image={image} error={dropError || errors.image} onChange={(next) => { setImage(next); setErrors((current) => ({ ...current, image: undefined })); }} onError={setDropError}/></div><div className="rounded-2xl border border-line bg-surface p-5 shadow-sm"><h2 className="text-lg font-semibold">Informações da posição</h2><p className="mt-1 text-sm text-muted"><span className="font-semibold text-red-700">*</span> Campos obrigatórios</p><div className="mt-5 grid gap-4 sm:grid-cols-2">
    <Field id="title" label="Título" required error={errors.title}><input id="title" value={values.title} aria-invalid={Boolean(errors.title)} onChange={(event) => update("title", event.target.value)} className={inputClass}/></Field>
    <Field id="date" label="Data" required error={errors.date}><input id="date" type="date" value={values.date} aria-invalid={Boolean(errors.date)} onChange={(event) => update("date", event.target.value)} className={inputClass}/></Field>
    <Field id="imageOrigin" label="Origem da imagem" required error={errors.imageOrigin}><select id="imageOrigin" value={values.imageOrigin} aria-invalid={Boolean(errors.imageOrigin)} onChange={(event) => { update("imageOrigin", event.target.value as UploadFormValues["imageOrigin"]); update("sourceContext", ""); update("sourceDetails", ""); }} className={inputClass}><option value="">Selecione</option>{Object.entries(imageOriginLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field>
    <Field id="sourceContext" label="Plataforma ou contexto" required error={errors.sourceContext}><select id="sourceContext" disabled={!contexts} value={values.sourceContext} aria-invalid={Boolean(errors.sourceContext)} onChange={(event) => { update("sourceContext", event.target.value as PositionSourceContext | ""); update("sourceDetails", ""); }} className={inputClass}><option value="">{contexts ? "Selecione" : "Escolha primeiro a origem"}</option>{contexts && Object.entries(contexts).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field>
    {values.sourceContext === "other" && <Field id="sourceDetails" label="Detalhes da plataforma ou contexto" required error={errors.sourceDetails}><input id="sourceDetails" value={values.sourceDetails} aria-invalid={Boolean(errors.sourceDetails)} onChange={(event) => update("sourceDetails", event.target.value)} className={inputClass}/></Field>}
    <div className="sm:col-span-2"><label htmlFor="description" className="text-sm font-semibold">Descrição ou observações</label><textarea id="description" rows={4} value={values.description} onChange={(event) => update("description", event.target.value)} className={`${inputClass} resize-y`}/></div>
    <div className="sm:col-span-2"><label htmlFor="linkedGameId" className="text-sm font-semibold">Vincular a uma partida existente (opcional)</label><select id="linkedGameId" value={values.linkedGameId} onChange={(event) => update("linkedGameId", event.target.value)} className={inputClass}><option value="">Sem vínculo</option>{games.map((game) => <option key={game.id} value={game.id}>{game.title}</option>)}</select></div>
    <TagInput tags={values.tags} error={errors.tags} onChange={(tags) => update("tags", tags)}/>
  </div></div></div><div className="rounded-2xl border border-line bg-neutral-950 p-5 text-white"><p className="font-semibold">Posição privada neste protótipo</p><p className="mt-1 text-sm leading-6 text-neutral-300">Somente os metadados são persistidos localmente. A posição não interfere no ranking, rating ou estatísticas públicas. Permissões reais dependerão de backend e autenticação.</p></div><button type="submit" disabled={saving} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-neutral-950 px-5 py-3 text-sm font-semibold text-white hover:bg-neutral-800 focus-visible:outline-2 focus-visible:outline-offset-2 disabled:cursor-wait disabled:opacity-60 sm:w-auto"><Save size={17}/>{saving ? "Salvando..." : "Salvar posição"}</button></form>;
}
function Field({ id, label, required, error, children }: { id: string; label: string; required?: boolean; error?: string; children: React.ReactNode }) { return <div><label htmlFor={id} className="text-sm font-semibold">{label}{required && <span className="text-red-700"> *</span>}</label>{children}<FormFieldError id={`${id}-error`} message={error}/></div>; }
