import { useMemo, useState } from "react";
import { Search, X } from "lucide-react";
import { currentUser } from "@/lib/data/users";
import { availablePlayers, openMatchRooms, timeControls } from "@/lib/data/play";
import type { DemoColorChoice, DemoMatchConfig, OpenMatchRoom, RatingRangeOption } from "@/lib/types/play";
import { canEnterRoom, ratingDifference, ratingLimits } from "@/lib/utils/matchmaking";
import { assignedColor, buttonBase } from "./play";

type SortOption = "recent" | "near" | "low" | "high";
export function OpenMatchRooms({ randomIndex, onStart }: { randomIndex: number; onStart: (config: DemoMatchConfig) => void }) {
  const [localRooms, setLocalRooms] = useState<OpenMatchRoom[]>([]);
  const [query, setQuery] = useState(""); const [control, setControl] = useState("all"); const [category, setCategory] = useState("all");
  const [compatible, setCompatible] = useState(false); const [sort, setSort] = useState<SortOption>("recent"); const [creating, setCreating] = useState(false);
  const [ownControl, setOwnControl] = useState("10-0"); const [ownColor, setOwnColor] = useState<DemoColorChoice>("random"); const [ownRange, setOwnRange] = useState<RatingRangeOption>("200");
  const rooms = useMemo(() => [...localRooms, ...openMatchRooms].filter((room) => room.creatorName.toLocaleLowerCase("pt-BR").includes(query.trim().toLocaleLowerCase("pt-BR")) && (control === "all" || room.timeControl.id === control) && (category === "all" || room.category === category) && (!compatible || canEnterRoom(room, currentUser.id, currentUser.currentPlatformRating).allowed)).sort((a, b) => sort === "recent" ? b.createdAt.localeCompare(a.createdAt) : sort === "near" ? Math.abs(a.creatorRating-currentUser.currentPlatformRating)-Math.abs(b.creatorRating-currentUser.currentPlatformRating) : sort === "low" ? a.creatorRating-b.creatorRating : b.creatorRating-a.creatorRating), [localRooms, query, control, category, compatible, sort]);
  const enter = (room: OpenMatchRoom) => { const opponent = availablePlayers.find((player) => player.id === room.creatorPlayerId); if (!opponent || !canEnterRoom(room, currentUser.id, currentUser.currentPlatformRating).allowed) return; const userColor = room.colorPreference === "white" ? "black" : room.colorPreference === "black" ? "white" : assignedColor("random", randomIndex); onStart({ opponent, timeControl: room.timeControl, userColor }); };
  const createRoom = () => { const timeControl = timeControls.find((item) => item.id === ownControl) ?? timeControls[0]; const limits = ratingLimits(currentUser.currentPlatformRating, ownRange); setLocalRooms((items) => [{ id: `local-room-${Date.now()}`, creatorPlayerId: currentUser.id, creatorName: currentUser.name, creatorRating: currentUser.currentPlatformRating, region: "Brasil", timeControl, category: timeControl.category, colorPreference: ownColor, minRating: limits.min, maxRating: limits.max, createdAt: new Date().toISOString(), status: "open", isDemo: true, isOwn: true }, ...items]); setCreating(false); };
  const clear = () => { setQuery(""); setControl("all"); setCategory("all"); setCompatible(false); setSort("recent"); };
  return <div className="space-y-5"><section className="rounded-2xl border border-line bg-surface p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-xl font-bold">Salas abertas</h2><p className="mt-1 text-sm text-muted">Escolha um desafio público fictício compatível com seu rating.</p><p className="mt-2 text-sm font-semibold">Estas salas são simuladas. Nenhum jogador real está conectado.</p></div><button type="button" onClick={() => setCreating((value) => !value)} className={`${buttonBase} bg-neutral-950 text-white`}>Abrir minha sala</button></div>
    {creating && <div className="mt-5 rounded-2xl border border-line bg-neutral-100 p-4"><h3 className="font-semibold">Nova sala local</h3><p className="mt-1 text-sm text-muted">Esta sala existe apenas localmente e nenhum outro usuário pode vê-la.</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><label className="text-sm font-semibold">Controle<select value={ownControl} onChange={(e) => setOwnControl(e.target.value)} className="mt-1 w-full rounded-xl border border-line bg-white p-2.5">{timeControls.map((item) => <option key={item.id} value={item.id}>{item.minutes} + {item.increment}</option>)}</select></label><label className="text-sm font-semibold">Sua preferência de cor<select value={ownColor} onChange={(e) => setOwnColor(e.target.value as DemoColorChoice)} className="mt-1 w-full rounded-xl border border-line bg-white p-2.5"><option value="white">Brancas</option><option value="black">Pretas</option><option value="random">Aleatória</option></select></label><label className="text-sm font-semibold">Faixa aceita<select value={ownRange} onChange={(e) => setOwnRange(e.target.value as RatingRangeOption)} className="mt-1 w-full rounded-xl border border-line bg-white p-2.5"><option value="100">±100</option><option value="200">±200</option><option value="400">±400</option><option value="unlimited">Sem limite</option></select></label></div><div className="mt-4 flex gap-2"><button type="button" onClick={createRoom} className={`${buttonBase} bg-neutral-950 text-white`}>Criar sala simulada</button><button type="button" onClick={() => setCreating(false)} className={`${buttonBase} border border-line bg-white`}>Cancelar</button></div></div>}
    <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="relative"><span className="sr-only">Buscar jogador</span><Search size={17} className="absolute left-3 top-3"/><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar jogador" className="w-full rounded-xl border border-line py-2.5 pl-9 pr-3"/></label><select aria-label="Filtrar controle" value={control} onChange={(e) => setControl(e.target.value)} className="rounded-xl border border-line bg-white p-2.5"><option value="all">Todos os controles</option>{timeControls.map((item) => <option key={item.id} value={item.id}>{item.minutes} + {item.increment}</option>)}</select><select aria-label="Filtrar categoria" value={category} onChange={(e) => setCategory(e.target.value)} className="rounded-xl border border-line bg-white p-2.5"><option value="all">Todas as categorias</option><option>Bullet</option><option>Blitz</option><option>Rápida</option></select><select aria-label="Ordenar salas" value={sort} onChange={(e) => setSort(e.target.value as SortOption)} className="rounded-xl border border-line bg-white p-2.5"><option value="recent">Mais recentes</option><option value="near">Rating mais próximo</option><option value="low">Menor rating</option><option value="high">Maior rating</option></select></div><div className="mt-3 flex flex-wrap items-center justify-between gap-3"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={compatible} onChange={(e) => setCompatible(e.target.checked)}/> Compatíveis com meu rating</label><button type="button" onClick={clear} className={`${buttonBase} inline-flex items-center gap-2 border border-line bg-white`}><X size={16}/>Limpar filtros</button></div></section>
    <div className="grid gap-4 lg:grid-cols-2">{rooms.map((room) => { const eligibility = canEnterRoom(room, currentUser.id, currentUser.currentPlatformRating); const difference = ratingDifference(room.creatorRating, currentUser.currentPlatformRating); const availableColor = room.colorPreference === "white" ? "Pretas" : room.colorPreference === "black" ? "Brancas" : "Aleatória"; return <article key={room.id} className="rounded-2xl border border-line bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{room.creatorName} {room.isOwn && <span className="ml-1 rounded-full bg-neutral-950 px-2 py-1 text-xs text-white">Sua sala</span>}</h3><p className="text-sm text-muted">Rating {room.creatorRating} · {difference > 0 ? "+" : ""}{difference} · {room.region}</p></div><span className="rounded-full border border-line px-2 py-1 text-xs font-bold">{room.status === "open" ? "Aberta" : room.status === "occupied" ? "Ocupada" : "Cancelada"}</span></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-muted">Controle</dt><dd className="font-semibold">{room.timeControl.minutes} + {room.timeControl.increment} · {room.category}</dd></div><div><dt className="text-muted">Sua cor</dt><dd className="font-semibold">{availableColor}</dd></div><div><dt className="text-muted">Faixa aceita</dt><dd className="font-semibold">{room.minRating}–{room.maxRating}</dd></div><div><dt className="text-muted">Criada</dt><dd className="font-semibold">{new Date(room.createdAt).toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" })}</dd></div></dl>{!eligibility.allowed && <p className="mt-3 text-sm text-red-700">{eligibility.reason}</p>}{room.isOwn ? <button type="button" onClick={() => setLocalRooms((items) => items.filter((item) => item.id !== room.id))} className={`${buttonBase} mt-4 w-full border border-red-300 text-red-700`}>Cancelar minha sala</button> : <button type="button" disabled={!eligibility.allowed} onClick={() => enter(room)} className={`${buttonBase} mt-4 w-full bg-neutral-950 text-white`}>Entrar na sala</button>}</article>; })}</div>{!rooms.length && <div role="status" className="rounded-2xl border border-dashed border-line p-8 text-center">Nenhuma sala corresponde aos filtros.</div>}</div>;
}
