import { ArrowUp, ShieldCheck } from "lucide-react";
import type { RankingPlayer } from "@/lib/types/chess";
import { formatPercent, positionChange } from "./ranking";

export function CurrentUserRankingCard({ player, playerAbove }: { player: RankingPlayer; playerAbove?: RankingPlayer }) {
  const distance = playerAbove ? Math.max(0, playerAbove.currentPlatformRating - player.currentPlatformRating) : null;
  const movement = positionChange(player);
  const metrics = [{ label: "Posição atual", value: `${player.position}º` }, { label: "Rating oficial", value: player.currentPlatformRating }, { label: "Partidas oficiais", value: player.platformGames }, { label: "Vitórias", value: player.wins }, { label: "Derrotas", value: player.losses }, { label: "Empates", value: player.draws }, { label: "Taxa de vitória", value: formatPercent(player.winRate) }];
  return <section aria-labelledby="your-position-title" className="overflow-hidden rounded-2xl border-2 border-neutral-950 bg-white shadow-sm"><div className="flex flex-col gap-3 bg-neutral-950 p-5 text-white sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-neutral-400">Classificação oficial</p><h2 id="your-position-title" className="mt-1 text-xl font-semibold">Sua posição</h2></div><span className="inline-flex w-fit items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-sm"><ShieldCheck size={16} aria-hidden="true" />Somente partidas da plataforma</span></div><div className="grid grid-cols-2 gap-px bg-line sm:grid-cols-4 lg:grid-cols-7">{metrics.map((metric) => <div key={metric.label} className="bg-white p-4"><p className="text-xs text-muted">{metric.label}</p><p className="mt-1 text-xl font-bold tabular-nums">{metric.value}</p></div>)}</div><div className="flex flex-col gap-2 border-t border-line bg-neutral-50 px-5 py-4 text-sm sm:flex-row sm:items-center sm:justify-between"><span><strong>{movement.symbol} {movement.text}</strong></span><span className="inline-flex items-center gap-2 text-neutral-700"><ArrowUp size={15} aria-hidden="true" />{distance === null ? "Você lidera o ranking" : `${distance} ponto${distance === 1 ? "" : "s"} para o jogador acima`}</span></div></section>;
}
