import { Eye } from "lucide-react";
import type { RankingPlayer } from "@/lib/types/chess";
import { formatPercent, getInitials, levelLabels, positionChange, streakLabel } from "./ranking";

export function RankingTable({ players, onProfile }: { players: RankingPlayer[]; onProfile: (player: RankingPlayer) => void }) {
  return <><div className="hidden max-w-full overflow-x-auto rounded-2xl border border-line bg-white shadow-sm lg:block"><table className="w-full min-w-[1180px] border-collapse text-left text-sm"><caption className="sr-only">Classificação oficial da comunidade TeaChess</caption><thead className="bg-neutral-950 text-xs uppercase tracking-wide text-white"><tr>{["Posição oficial","Jogador","Região","Rating","Partidas oficiais","Vitórias","Derrotas","Empates","Taxa de vitória","Sequência","Nível","Ação"].map((heading) => <th key={heading} scope="col" className="whitespace-nowrap px-3 py-3.5 font-semibold">{heading}</th>)}</tr></thead><tbody className="divide-y divide-line">{players.map((player) => { const movement = positionChange(player); return <tr key={player.id} className={player.isCurrentUser ? "bg-neutral-100" : "hover:bg-neutral-50"}><td className="px-3 py-4"><span className="font-bold tabular-nums">{player.position}º</span><span className="mt-1 block whitespace-nowrap text-xs text-muted" title={movement.text}>{movement.symbol} {movement.text}</span></td><td className="px-3 py-4"><div className="flex min-w-44 items-center gap-3"><span className="flex size-9 shrink-0 items-center justify-center rounded-full bg-neutral-900 text-xs font-bold text-white">{getInitials(player.name)}</span><span><strong className="block">{player.name}</strong>{player.isCurrentUser && <span className="mt-1 inline-block rounded-full bg-neutral-950 px-2 py-0.5 text-[11px] font-bold text-white">Você</span>}</span></div></td><Cell value={player.region} /><Cell value={player.currentPlatformRating} strong /><Cell value={player.platformGames} /><Cell value={player.wins} /><Cell value={player.losses} /><Cell value={player.draws} /><Cell value={formatPercent(player.winRate)} /><Cell value={streakLabel(player.currentStreak)} /><Cell value={levelLabels[player.level]} /><td className="px-3 py-3"><ProfileButton player={player} onProfile={onProfile} /></td></tr>; })}</tbody></table></div><div className="grid gap-3 lg:hidden">{players.map((player) => <RankingPlayerCard key={player.id} player={player} onProfile={onProfile} />)}</div></>;
}

function Cell({ value, strong = false }: { value: string | number; strong?: boolean }) { return <td className={`whitespace-nowrap px-3 py-4 tabular-nums ${strong ? "font-bold" : ""}`}>{value}</td>; }
function ProfileButton({ player, onProfile }: { player: RankingPlayer; onProfile: (player: RankingPlayer) => void }) { return <button type="button" onClick={() => onProfile(player)} className="inline-flex min-h-10 whitespace-nowrap items-center gap-2 rounded-xl border border-line px-3 text-sm font-semibold hover:bg-neutral-100 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-focus"><Eye size={15} aria-hidden="true" />Ver perfil</button>; }

function RankingPlayerCard({ player, onProfile }: { player: RankingPlayer; onProfile: (player: RankingPlayer) => void }) {
  const movement = positionChange(player);
  return <article className={`min-w-0 rounded-2xl border bg-white p-4 shadow-sm ${player.isCurrentUser ? "border-2 border-neutral-950" : "border-line"}`}><div className="flex min-w-0 items-start justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><span className="flex size-10 shrink-0 items-center justify-center rounded-full bg-neutral-950 text-xs font-bold text-white">{getInitials(player.name)}</span><div className="min-w-0"><h3 className="truncate font-semibold">{player.name}</h3><p className="text-sm text-muted">{player.region} · {levelLabels[player.level]}</p></div></div><div className="shrink-0 text-right"><p className="text-xl font-bold">{player.position}º</p><p className="text-xs text-muted">Posição oficial</p></div></div><div className="mt-3 flex flex-wrap items-center gap-2 text-xs"><span className="rounded-full border border-line px-2 py-1">{movement.symbol} {movement.text}</span>{player.isCurrentUser && <span className="rounded-full bg-neutral-950 px-2 py-1 font-bold text-white">Você</span>}</div><dl className="mt-4 grid grid-cols-2 gap-3 border-y border-line py-4 text-sm sm:grid-cols-4"><Metric label="Rating" value={player.currentPlatformRating} /><Metric label="Partidas" value={player.platformGames} /><Metric label="Vitórias" value={player.wins} /><Metric label="Derrotas" value={player.losses} /><Metric label="Empates" value={player.draws} /><Metric label="Taxa de vitória" value={formatPercent(player.winRate)} /><div className="col-span-2"><Metric label="Sequência" value={streakLabel(player.currentStreak)} /></div></dl><div className="mt-4 flex justify-end"><ProfileButton player={player} onProfile={onProfile} /></div></article>;
}
function Metric({ label, value }: { label: string; value: string | number }) { return <div><dt className="text-xs text-muted">{label}</dt><dd className="mt-1 font-semibold tabular-nums">{value}</dd></div>; }
