"use client";
import { ShieldCheck, X } from "lucide-react";
import { useEffect, useRef } from "react";

export function RankingRulesDialog({ open, onClose }: { open: boolean; onClose: () => void }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { const dialog = ref.current; if (open && !dialog?.open) dialog?.showModal(); if (!open && dialog?.open) dialog.close(); }, [open]);
  return <dialog ref={ref} onCancel={(event) => { event.preventDefault(); onClose(); }} onClose={onClose} aria-labelledby="ranking-rules-title" aria-describedby="ranking-rules-description" className="m-auto max-h-[90vh] w-[calc(100%-2rem)] max-w-xl overflow-y-auto rounded-2xl border border-line bg-white p-0 shadow-2xl backdrop:bg-black/60"><div className="flex items-start justify-between gap-4 border-b border-line p-5"><div><span className="flex size-10 items-center justify-center rounded-full bg-neutral-100"><ShieldCheck size={19} aria-hidden="true" /></span><h2 id="ranking-rules-title" className="mt-3 text-xl font-semibold">Como funciona o ranking</h2></div><button type="button" onClick={onClose} aria-label="Fechar regras do ranking" className="rounded-lg p-2 hover:bg-neutral-100 focus-visible:outline-2 focus-visible:outline-focus"><X size={20} /></button></div><div id="ranking-rules-description" className="space-y-4 p-5 text-sm leading-6 text-neutral-700"><ul className="list-disc space-y-2 pl-5"><li>Somente partidas realizadas na plataforma contam para a classificação e suas estatísticas.</li><li>Partidas externas permanecem privadas e não contam para rating, posição, resultados ou taxa de vitória.</li><li>O rating exibido é o rating oficial atual do perfil TeaChess.</li><li>Os critérios de desempate e o histórico de posições são simulados nesta versão.</li><li>O sistema competitivo real, seus cálculos e sua validação serão implementados futuramente.</li></ul><p className="rounded-xl bg-neutral-100 p-4 font-medium text-neutral-900">Treinamentos, uploads e análises também não alteram o ranking.</p></div><div className="flex justify-end border-t border-line bg-neutral-50 p-4"><button type="button" onClick={onClose} className="rounded-xl bg-neutral-950 px-4 py-2.5 text-sm font-semibold text-white focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-focus">Entendi</button></div></dialog>;
}
