import { Eye, UserRoundCheck } from "lucide-react";
import type { RankingPlayer } from "@/lib/types/chess";
import { formatPercent, getInitials, positionChange } from "./ranking";
import { RankingStreak } from "./RankingStreak";

export function RankingTable({ players, onProfile }: { players: RankingPlayer[]; onProfile: (player: RankingPlayer) => void }) {
  return <><div className="hidden max-w-full overflow-x-auto rounded-2xl border border-line bg-white shadow-sm lg:block"><table className="w-full min-w-[1040px] table-fixed border-collapse text-left text-sm"><caption className="sr-only">Classificação oficial da comunidade TeaChess</caption><colgroup><col className="w-[12%]" /><col className="w-[20%]" /><col className="w-[10%]" /><col className="w-[8%]" /><col className="w-[8%]" /><col className="w-[4%]" /><col className="w-[4%]" /><col className="w-[4%]" /><col className="w-[10%]" /><col className="w-[9%]" /><col className="w-[11%]" /></colgroup><thead className="bg-neutral-950 text-xs uppercase tracking-wide text-white"><tr><Heading>Posição oficial</Heading><Heading>Jogador</Heading><Heading>Região</Heading><NumericHeading label="Rating" /><NumericHeading label="Partidas" /><NumericHeading label="V" accessibleLabel="Vitórias" /><NumericHeading label="D" accessibleLabel="Derrotas" /><NumericHeading label="E" accessibleLabel="Empates" /><NumericHeading label="%" accessibleLabel="Taxa de vitória" /><Heading>Sequência</Heading><Heading>Ação</Heading></tr></thead><tbody className="divide-y divide-line">{players.map((player) => { const movement = positionChange(player); return <tr key={player.id} className={player.isCurrentUser ? "border-l-4 border-l-green-700 bg-green-50/80" : "hover:bg-neutral-50"}><td className="px-3 py-4"><span className="font-bold tabular-nums">{player.position}º</span><span className="mt-1 block whitespace-nowrap text-xs text-muted" title={movement.text}>{movement.symbol} {movement.text}</span></td><td className="px-3 py-4"><div className="flex min-w-0 items-center gap-3"><span className="flex size-9 shrink-0 items-center justify-center rounded-full bg-neutral-900 text-xs font-bold text-white" aria-hidden="true">{getInitials(player.name)}</span><span className="min-w-0"><strong className="block truncate">{player.name}</strong>{player.isCurrentUser && <YouBadge />}</span></div></td><Cell value={player.region} /><NumericCell value={player.currentPlatformRating} strong /><NumericCell value={player.platformGames} /><NumericCell value={player.wins} /><NumericCell value={player.losses} /><NumericCell value={player.draws} /><NumericCell value={formatPercent(player.winRate)} /><td className="px-3 py-4"><RankingStreak streak={player.currentStreak} abbreviated /></td><td className="px-3 py-3"><ProfileButton player={player} onProfile={onProfile} /></td></tr>; })}</tbody></table></div><div className="grid gap-3 lg:hidden">{players.map((player) => <RankingPlayerCard key={player.id} player={player} onProfile={onProfile} />)}</div></>;
}

function Heading({ children }: { children: React.ReactNode }) { return <th scope="col" className="whitespace-nowrap px-3 py-3.5 font-semibold">{children}</th>; }
function NumericHeading({ label, accessibleLabel }: { label: string; accessibleLabel?: string }) { return <th scope="col" className="whitespace-nowrap px-2 py-3.5 text-center font-semibold tabular-nums" title={accessibleLabel}><span aria-hidden={accessibleLabel ? "true" : undefined}>{label}</span>{accessibleLabel && <span className="sr-only">{accessibleLabel}</span>}</th>; }
function Cell({ value }: { value: string | number }) { return <td className="whitespace-nowrap px-3 py-4">{value}</td>; }
function NumericCell({ value, strong = false }: { value: string | number; strong?: boolean }) { return <td className={`whitespace-nowrap px-2 py-4 text-center tabular-nums ${strong ? "font-bold" : ""}`}>{value}</td>; }
function YouBadge() { return <span className="mt-1 inline-flex items-center gap-1 rounded-full bg-green-700 px-2 py-0.5 text-[11px] font-bold text-white"><UserRoundCheck size={12} aria-hidden="true" />Você</span>; }
function ProfileButton({ player, onProfile }: { player: RankingPlayer; onProfile: (player: RankingPlayer) => void }) { return <button type="button" onClick={() => onProfile(player)} className="inline-flex min-h-10 whitespace-nowrap items-center gap-2 rounded-xl border border-line bg-white px-3 text-sm font-semibold hover:bg-neutral-100 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-focus"><Eye size={15} aria-hidden="true" />Ver perfil</button>; }

function RankingPlayerCard({ player, onProfile }: { player: RankingPlayer; onProfile: (player: RankingPlayer) => void }) {
  const movement = positionChange(player);
  return <article className={`min-w-0 rounded-2xl border bg-white p-4 shadow-sm ${player.isCurrentUser ? "border-l-4 border-green-700 bg-green-50/80" : "border-line"}`}><div className="flex min-w-0 items-start justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><span className="flex size-10 shrink-0 items-center justify-center rounded-full bg-neutral-950 text-xs font-bold text-white" aria-hidden="true">{getInitials(player.name)}</span><div className="min-w-0"><h3 className="truncate font-semibold">{player.name}</h3><p className="text-sm text-muted">{player.region}</p></div></div><div className="shrink-0 text-right"><p className="text-xl font-bold">{player.position}º</p><p className="text-xs text-muted">Posição oficial</p></div></div><div className="mt-3 flex flex-wrap items-center gap-2 text-xs"><span className="rounded-full border border-line bg-white px-2 py-1">{movement.symbol} {movement.text}</span>{player.isCurrentUser && <YouBadge />}</div><dl className="mt-4 grid grid-cols-2 gap-3 border-y border-line py-4 text-sm"><Metric label="Rating" value={player.currentPlatformRating} /><Metric label="Partidas" value={player.platformGames} /><div className="col-span-2 grid grid-cols-3 rounded-xl bg-white/80 p-3 text-center"><Metric label="V" accessibleLabel="Vitórias" value={player.wins} /><Metric label="D" accessibleLabel="Derrotas" value={player.losses} /><Metric label="E" accessibleLabel="Empates" value={player.draws} /></div><Metric label="Taxa de vitória" value={formatPercent(player.winRate)} /><div><dt className="text-xs text-muted">Sequência</dt><dd className="mt-1 tabular-nums"><RankingStreak streak={player.currentStreak} abbreviated /></dd></div></dl><div className="mt-4 flex justify-end"><ProfileButton player={player} onProfile={onProfile} /></div></article>;
}
function Metric({ label, accessibleLabel, value }: { label: string; accessibleLabel?: string; value: string | number }) { return <div><dt className="text-xs text-muted" aria-label={accessibleLabel}>{label}</dt><dd className="mt-1 font-semibold tabular-nums">{value}</dd></div>; }
