import type { ChessTitle, HumanTeacher, LessonFormat } from "@/lib/types/humanTeachers";
export type PriceRange = "all" | "under-75" | "76-120" | "121-200" | "over-200";
export type AvailabilityRange = "all" | "today" | "three-days" | "week";
export type TitleGroup = "all" | "none" | "cm" | "fm" | "im" | "gm";
export type TeacherSort = "recommended" | "price-asc" | "price-desc" | "reviews" | "experience" | "availability";
export interface TeacherFilterState { query: string; specialty: string; format: "all" | LessonFormat; price: PriceRange; availability: AvailabilityRange; title: TitleGroup; sort: TeacherSort; }
export const initialTeacherFilters: TeacherFilterState = { query: "", specialty: "all", format: "all", price: "all", availability: "all", title: "all", sort: "recommended" };
export const currency = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
export const formatLabel = (format: LessonFormat): string => format === "ambos" ? "Online e presencial" : format[0].toUpperCase() + format.slice(1);
const titleMatches = (title: ChessTitle, group: TitleGroup) => group === "all" || (group === "none" ? title === "Sem título" : group === "cm" ? ["CM", "WCM"].includes(title) : group === "fm" ? ["FM", "WFM"].includes(title) : group === "im" ? ["IM", "WIM"].includes(title) : ["GM", "WGM"].includes(title));
const daysUntil = (date: string): number => Math.round((new Date(`${date}T12:00:00`).getTime() - new Date("2026-07-11T12:00:00").getTime()) / 86400000);
export const nextSlot = (teacher: HumanTeacher) => teacher.slots.find((slot) => slot.available);
export function filterTeachers(teachers: HumanTeacher[], filters: TeacherFilterState): HumanTeacher[] { const query = filters.query.trim().toLocaleLowerCase("pt-BR"); return teachers.filter((teacher) => { const haystack = [teacher.name, teacher.region, ...teacher.languages, ...teacher.specialties].join(" ").toLocaleLowerCase("pt-BR"); const price = filters.price === "all" || (filters.price === "under-75" ? teacher.price <= 75 : filters.price === "76-120" ? teacher.price >= 76 && teacher.price <= 120 : filters.price === "121-200" ? teacher.price >= 121 && teacher.price <= 200 : teacher.price > 200); const format = filters.format === "all" || teacher.format === filters.format || teacher.format === "ambos" && filters.format !== "ambos"; const slot = nextSlot(teacher); const days = slot ? daysUntil(slot.date) : 99; const availability = filters.availability === "all" || (filters.availability === "today" ? days === 0 : filters.availability === "three-days" ? days >= 0 && days <= 2 : days >= 0 && days <= 6); return (!query || haystack.includes(query)) && (filters.specialty === "all" || teacher.specialties.includes(filters.specialty as HumanTeacher["specialties"][number])) && format && price && availability && titleMatches(teacher.title, filters.title); }).sort((a, b) => filters.sort === "price-asc" ? a.price - b.price : filters.sort === "price-desc" ? b.price - a.price : filters.sort === "reviews" ? b.reviewScore - a.reviewScore || b.reviewCount - a.reviewCount : filters.sort === "experience" ? b.experienceYears - a.experienceYears : filters.sort === "availability" ? (nextSlot(a)?.date ?? "9999").localeCompare(nextSlot(b)?.date ?? "9999") : Number(b.verified) - Number(a.verified) || b.reviewScore - a.reviewScore || a.price - b.price); }
